/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration of base model architectures. For example, Stable Diffusion 1.x, Stable Diffusion 2.x, FLUX, etc.  Every model config must have a base architecture type.  Not all models are associated with a base architecture. For example, CLIP models are their own thing, not related to any particular model architecture. To simplify internal APIs and make it easier to work with models, we use a fallback/null value `BaseModelType.Any` for these models, instead of making the model base optional.
 */
export type BaseModelType = 'any' | 'sd-1' | 'sd-2' | 'sd-3' | 'sdxl' | 'sdxl-refiner' | 'flux' | 'flux2' | 'cogview4' | 'z-image' | 'unknown';

export const BaseModelType = {
    Any: 'any' as BaseModelType,
    Sd1: 'sd-1' as BaseModelType,
    Sd2: 'sd-2' as BaseModelType,
    Sd3: 'sd-3' as BaseModelType,
    Sdxl: 'sdxl' as BaseModelType,
    SdxlRefiner: 'sdxl-refiner' as BaseModelType,
    Flux: 'flux' as BaseModelType,
    Flux2: 'flux2' as BaseModelType,
    Cogview4: 'cogview4' as BaseModelType,
    ZImage: 'z-image' as BaseModelType,
    Unknown: 'unknown' as BaseModelType
};

