/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Adds typing data for discriminated union.
 */
export interface BaseMetadata { 
    /**
     * model\'s name
     */
    name: string;
    type?: BaseMetadata.TypeEnum;
}
export namespace BaseMetadata {
    export type TypeEnum = 'basemetadata';
    export const TypeEnum = {
        Basemetadata: 'basemetadata' as TypeEnum
    };
}


