/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Event model for batch_enqueued
 */
export interface BatchEnqueuedEvent { 
    /**
     * The timestamp of the event
     */
    timestamp: number;
    /**
     * The ID of the queue
     */
    queue_id: string;
    /**
     * The ID of the batch
     */
    batch_id: string;
    /**
     * The number of invocations enqueued
     */
    enqueued: number;
    /**
     * The number of invocations initially requested to be enqueued (may be less than enqueued if queue was full)
     */
    requested: number;
    /**
     * The priority of the batch
     */
    priority: number;
    origin: string | null;
}

