/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoardField } from './boardField';
import { ColorField } from './colorField';


/**
 * Creates a blank image and forwards it to the pipeline
 */
export interface BlankImageInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    /**
     * The width of the image
     */
    width?: number;
    /**
     * The height of the image
     */
    height?: number;
    /**
     * The mode of the image
     */
    mode?: BlankImageInvocation.ModeEnum;
    /**
     * The color of the image
     */
    color?: ColorField;
    type: BlankImageInvocation.TypeEnum;
}
export namespace BlankImageInvocation {
    export type ModeEnum = 'RGB' | 'RGBA';
    export const ModeEnum = {
        Rgb: 'RGB' as ModeEnum,
        Rgba: 'RGBA' as ModeEnum
    };
    export type TypeEnum = 'blank_image';
    export const TypeEnum = {
        BlankImage: 'blank_image' as TypeEnum
    };
}


