/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Batch } from './batch';


export interface BodyEnqueueBatch { 
    /**
     * Batch to process
     */
    batch: Batch;
    /**
     * Whether or not to prepend this batch in the queue
     */
    prepend?: boolean;
}

