/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A bounding box primitive value.
 */
export interface BoundingBoxField { 
    /**
     * The minimum x-coordinate of the bounding box (inclusive).
     */
    x_min: number;
    /**
     * The maximum x-coordinate of the bounding box (exclusive).
     */
    x_max: number;
    /**
     * The minimum y-coordinate of the bounding box (inclusive).
     */
    y_min: number;
    /**
     * The maximum y-coordinate of the bounding box (exclusive).
     */
    y_max: number;
    score?: number | null;
}

