/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response body for bulk model deletion.
 */
export interface BulkDeleteModelsResponse { 
    /**
     * List of successfully deleted model keys
     */
    deleted: Array<string>;
    /**
     * List of failed deletions with error messages
     */
    failed: Array<{ [key: string]: any; }>;
}

