/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CacheStats { 
    hits?: number;
    misses?: number;
    high_watermark?: number;
    in_cache?: number;
    cleared?: number;
    cache_size?: number;
    loaded_model_sizes?: { [key: string]: number; };
}

