/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Calculate the coordinates and overlaps of tiles that cover a target image shape.
 */
export interface CalculateImageTilesEvenSplitInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    /**
     * The image width, in pixels, to calculate tiles for.
     */
    image_width?: number;
    /**
     * The image height, in pixels, to calculate tiles for.
     */
    image_height?: number;
    /**
     * Number of tiles to divide image into on the x axis
     */
    num_tiles_x?: number;
    /**
     * Number of tiles to divide image into on the y axis
     */
    num_tiles_y?: number;
    /**
     * The overlap, in pixels, between adjacent tiles.
     */
    overlap?: number;
    type: CalculateImageTilesEvenSplitInvocation.TypeEnum;
}
export namespace CalculateImageTilesEvenSplitInvocation {
    export type TypeEnum = 'calculate_image_tiles_even_split';
    export const TypeEnum = {
        CalculateImageTilesEvenSplit: 'calculate_image_tiles_even_split' as TypeEnum
    };
}


