/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Calculate the coordinates and overlaps of tiles that cover a target image shape.
 */
export interface CalculateImageTilesMinimumOverlapInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    /**
     * The image width, in pixels, to calculate tiles for.
     */
    image_width?: number;
    /**
     * The image height, in pixels, to calculate tiles for.
     */
    image_height?: number;
    /**
     * The tile width, in pixels.
     */
    tile_width?: number;
    /**
     * The tile height, in pixels.
     */
    tile_height?: number;
    /**
     * Minimum overlap between adjacent tiles, in pixels.
     */
    min_overlap?: number;
    type: CalculateImageTilesMinimumOverlapInvocation.TypeEnum;
}
export namespace CalculateImageTilesMinimumOverlapInvocation {
    export type TypeEnum = 'calculate_image_tiles_min_overlap';
    export const TypeEnum = {
        CalculateImageTilesMinOverlap: 'calculate_image_tiles_min_overlap' as TypeEnum
    };
}


