/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CLIPField } from './cLIPField';


/**
 * Base class for invocations that output a CLIP field
 */
export interface CLIPOutput { 
    /**
     * CLIP (tokenizer, text encoder, LoRAs) and skipped layer count
     */
    clip: CLIPField;
    type: CLIPOutput.TypeEnum;
}
export namespace CLIPOutput {
    export type TypeEnum = 'clip_output';
    export const TypeEnum = {
        ClipOutput: 'clip_output' as TypeEnum
    };
}


