/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Variant type.
 */
export type ClipVariantType = 'large' | 'gigantic';

export const ClipVariantType = {
    Large: 'large' as ClipVariantType,
    Gigantic: 'gigantic' as ClipVariantType
};

