/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CLIPField } from './cLIPField';


/**
 * Skip layers in clip text_encoder model.
 */
export interface CLIPSkipInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    clip?: CLIPField | null;
    /**
     * Number of layers to skip in text encoder
     */
    skipped_layers?: number;
    type: CLIPSkipInvocation.TypeEnum;
}
export namespace CLIPSkipInvocation {
    export type TypeEnum = 'clip_skip';
    export const TypeEnum = {
        ClipSkip: 'clip_skip' as TypeEnum
    };
}


