/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VAEField } from './vAEField';
import { BoardField } from './boardField';
import { LatentsField } from './latentsField';


/**
 * Generates an image from latents.
 */
export interface CogView4LatentsToImageInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    latents?: LatentsField | null;
    vae?: VAEField | null;
    type: CogView4LatentsToImageInvocation.TypeEnum;
}
export namespace CogView4LatentsToImageInvocation {
    export type TypeEnum = 'cogview4_l2i';
    export const TypeEnum = {
        Cogview4L2i: 'cogview4_l2i' as TypeEnum
    };
}


