/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DenoiseMaskField } from './denoiseMaskField';
import { CogView4ConditioningField } from './cogView4ConditioningField';
import { BoardField } from './boardField';
import { LatentsField } from './latentsField';
import { CFGScale } from './cFGScale';
import { TransformerField } from './transformerField';


/**
 * Run the denoising process with a CogView4 model.
 */
export interface CogView4DenoiseInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    latents?: LatentsField | null;
    denoise_mask?: DenoiseMaskField | null;
    /**
     * When to start denoising, expressed a percentage of total steps
     */
    denoising_start?: number;
    /**
     * When to stop denoising, expressed a percentage of total steps
     */
    denoising_end?: number;
    transformer?: TransformerField | null;
    positive_conditioning?: CogView4ConditioningField | null;
    negative_conditioning?: CogView4ConditioningField | null;
    cfg_scale?: CFGScale;
    /**
     * Width of the generated image.
     */
    width?: number;
    /**
     * Height of the generated image.
     */
    height?: number;
    /**
     * Number of steps to run
     */
    steps?: number;
    /**
     * Randomness seed for reproducibility.
     */
    seed?: number;
    type: CogView4DenoiseInvocation.TypeEnum;
}
export namespace CogView4DenoiseInvocation {
    export type TypeEnum = 'cogview4_denoise';
    export const TypeEnum = {
        Cogview4Denoise: 'cogview4_denoise' as TypeEnum
    };
}


