/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Matches the color histogram of a base image to a reference image, optionally using a mask to only color-correct certain regions of the base image.
 */
export interface ColorCorrectInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    base_image?: ImageField | null;
    color_reference?: ImageField | null;
    mask?: ImageField | null;
    /**
     * Colorspace in which to apply histogram matching
     */
    colorspace?: ColorCorrectInvocation.ColorspaceEnum;
    type: ColorCorrectInvocation.TypeEnum;
}
export namespace ColorCorrectInvocation {
    export type ColorspaceEnum = 'RGB' | 'YCbCr' | 'YCbCr-Chroma' | 'YCbCr-Luma';
    export const ColorspaceEnum = {
        Rgb: 'RGB' as ColorspaceEnum,
        YcbCr: 'YCbCr' as ColorspaceEnum,
        YcbCrChroma: 'YCbCr-Chroma' as ColorspaceEnum,
        YcbCrLuma: 'YCbCr-Luma' as ColorspaceEnum
    };
    export type TypeEnum = 'color_correct';
    export const TypeEnum = {
        ColorCorrect: 'color_correct' as TypeEnum
    };
}


