/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColorField } from './colorField';


/**
 * Base class for nodes that output a collection of colors
 */
export interface ColorCollectionOutput { 
    /**
     * The output colors
     */
    collection: Array<ColorField>;
    type: ColorCollectionOutput.TypeEnum;
}
export namespace ColorCollectionOutput {
    export type TypeEnum = 'color_collection_output';
    export const TypeEnum = {
        ColorCollectionOutput: 'color_collection_output' as TypeEnum
    };
}


