/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColorField } from './colorField';


/**
 * A color primitive value
 */
export interface ColorInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    /**
     * The color value
     */
    color?: ColorField;
    type: ColorInvocation.TypeEnum;
}
export namespace ColorInvocation {
    export type TypeEnum = 'color';
    export const TypeEnum = {
        Color: 'color' as TypeEnum
    };
}


