/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConditioningField } from './conditioningField';


/**
 * Base class for nodes that output a single conditioning tensor
 */
export interface ConditioningOutput { 
    /**
     * Conditioning tensor
     */
    conditioning: ConditioningField;
    type: ConditioningOutput.TypeEnum;
}
export namespace ConditioningOutput {
    export type TypeEnum = 'conditioning_output';
    export const TypeEnum = {
        ConditioningOutput: 'conditioning_output' as TypeEnum
    };
}


