/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { ControlField } from './controlField';
import { ModelIdentifierField } from './modelIdentifierField';
import { ControlWeight } from './controlWeight';


/**
 * ControlNet(s) to apply
 */
export interface ControlNetList { 
    /**
     * The control image
     */
    image: ImageField;
    /**
     * The ControlNet model to use
     */
    control_model: ModelIdentifierField;
    control_weight?: ControlWeight;
    /**
     * When the ControlNet is first applied (% of total steps)
     */
    begin_step_percent?: number;
    /**
     * When the ControlNet is last applied (% of total steps)
     */
    end_step_percent?: number;
    /**
     * The control mode to use
     */
    control_mode?: ControlNetList.ControlModeEnum;
    /**
     * The resize mode to use
     */
    resize_mode?: ControlNetList.ResizeModeEnum;
}
export namespace ControlNetList {
    export type ControlModeEnum = 'balanced' | 'more_prompt' | 'more_control' | 'unbalanced';
    export const ControlModeEnum = {
        Balanced: 'balanced' as ControlModeEnum,
        MorePrompt: 'more_prompt' as ControlModeEnum,
        MoreControl: 'more_control' as ControlModeEnum,
        Unbalanced: 'unbalanced' as ControlModeEnum
    };
    export type ResizeModeEnum = 'just_resize' | 'crop_resize' | 'fill_resize' | 'just_resize_simple';
    export const ResizeModeEnum = {
        JustResize: 'just_resize' as ResizeModeEnum,
        CropResize: 'crop_resize' as ResizeModeEnum,
        FillResize: 'fill_resize' as ResizeModeEnum,
        JustResizeSimple: 'just_resize_simple' as ResizeModeEnum
    };
}


