/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelSourceType } from './modelSourceType';
import { ControlAdapterDefaultSettings } from './controlAdapterDefaultSettings';


/**
 * Model config for Z-Image Control adapter models (Safetensors checkpoint).  Z-Image Control models are standalone adapters containing only the control layers (control_layers, control_all_x_embedder, control_noise_refiner) that extend the base Z-Image transformer with spatial conditioning capabilities.  Supports: Canny, HED, Depth, Pose, MLSD. Recommended control_context_scale: 0.65-0.80.
 */
export interface ControlNetCheckpointZImageConfig { 
    /**
     * A unique key for this model.
     */
    key: string;
    /**
     * The hash of the model file(s).
     */
    hash: string;
    /**
     * Path to the model on the filesystem. Relative paths are relative to the Invoke root directory.
     */
    path: string;
    /**
     * The size of the model in bytes.
     */
    file_size: number;
    /**
     * Name of the model.
     */
    name: string;
    description: string | null;
    /**
     * The original source of the model (path, URL or repo_id).
     */
    source: string;
    /**
     * The type of source
     */
    source_type: ModelSourceType;
    source_api_response: string | null;
    cover_image: string | null;
    config_path: string | null;
    type: ControlNetCheckpointZImageConfig.TypeEnum;
    format: ControlNetCheckpointZImageConfig.FormatEnum;
    base: ControlNetCheckpointZImageConfig.BaseEnum;
    default_settings: ControlAdapterDefaultSettings | null;
}
export namespace ControlNetCheckpointZImageConfig {
    export type TypeEnum = 'controlnet';
    export const TypeEnum = {
        Controlnet: 'controlnet' as TypeEnum
    };
    export type FormatEnum = 'checkpoint';
    export const FormatEnum = {
        Checkpoint: 'checkpoint' as FormatEnum
    };
    export type BaseEnum = 'z-image';
    export const BaseEnum = {
        ZImage: 'z-image' as BaseEnum
    };
}


