/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoundingBoxField } from './boundingBoxField';
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Crop an image to the given bounding box. If the bounding box is omitted, the image is cropped to the non-transparent pixels.
 */
export interface CropImageToBoundingBoxInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    bounding_box?: BoundingBoxField | null;
    type: CropImageToBoundingBoxInvocation.TypeEnum;
}
export namespace CropImageToBoundingBoxInvocation {
    export type TypeEnum = 'crop_image_to_bounding_box';
    export const TypeEnum = {
        CropImageToBoundingBox: 'crop_image_to_bounding_box' as TypeEnum
    };
}


