/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeleteBoardResult { 
    /**
     * The id of the board that was deleted.
     */
    board_id: string;
    /**
     * The image names of the board-images relationships that were deleted.
     */
    deleted_board_images: Array<string>;
    /**
     * The names of the images that were deleted.
     */
    deleted_images: Array<string>;
}

