/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response from deleting orphaned models.
 */
export interface DeleteOrphanedModelsResponse { 
    /**
     * Paths that were successfully deleted
     */
    deleted: Array<string>;
    /**
     * Paths that had errors, with error messages
     */
    errors: { [key: string]: string; };
}

