/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An inpaint mask field
 */
export interface DenoiseMaskField { 
    /**
     * The name of the mask image
     */
    mask_name: string;
    masked_latents_name?: string | null;
    /**
     * Used for gradient inpainting
     */
    gradient?: boolean;
}

