/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DenoiseMaskField } from './denoiseMaskField';


/**
 * Base class for nodes that output a single image
 */
export interface DenoiseMaskOutput { 
    /**
     * Mask for denoise model run
     */
    denoise_mask: DenoiseMaskField;
    type: DenoiseMaskOutput.TypeEnum;
}
export namespace DenoiseMaskOutput {
    export type TypeEnum = 'denoise_mask_output';
    export const TypeEnum = {
        DenoiseMaskOutput: 'denoise_mask_output' as TypeEnum
    };
}


