/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * State of a download job.
 */
export type DownloadJobStatus = 'waiting' | 'running' | 'paused' | 'completed' | 'cancelled' | 'error';

export const DownloadJobStatus = {
    Waiting: 'waiting' as DownloadJobStatus,
    Running: 'running' as DownloadJobStatus,
    Paused: 'paused' as DownloadJobStatus,
    Completed: 'completed' as DownloadJobStatus,
    Cancelled: 'cancelled' as DownloadJobStatus,
    Error: 'error' as DownloadJobStatus
};

