/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Batch } from './batch';


export interface EnqueueBatchResult { 
    /**
     * The ID of the queue
     */
    queue_id: string;
    /**
     * The total number of queue items enqueued
     */
    enqueued: number;
    /**
     * The total number of queue items requested to be enqueued
     */
    requested: number;
    /**
     * The batch that was enqueued
     */
    batch: Batch;
    /**
     * The priority of the enqueued batch
     */
    priority: number;
    /**
     * The IDs of the queue items that were enqueued
     */
    item_ids: Array<number>;
}

