/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Expands a mask with a fade effect. The mask uses black to indicate areas to keep from the generated image and white for areas to discard. The mask is thresholded to create a binary mask, and then a distance transform is applied to create a fade effect. The fade size is specified in pixels, and the mask is expanded by that amount. The result is a mask with a smooth transition from black to white. If the fade size is 0, the mask is returned as-is.
 */
export interface ExpandMaskWithFadeInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    mask?: ImageField | null;
    /**
     * The threshold for the binary mask (0-255)
     */
    threshold?: number;
    /**
     * The size of the fade in pixels
     */
    fade_size_px?: number;
    type: ExpandMaskWithFadeInvocation.TypeEnum;
}
export namespace ExpandMaskWithFadeInvocation {
    export type TypeEnum = 'expand_mask_with_fade';
    export const TypeEnum = {
        ExpandMaskWithFade: 'expand_mask_with_fade' as TypeEnum
    };
}


