/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';


/**
 * Base class for FaceOff Output
 */
export interface FaceOffOutput { 
    /**
     * The output image
     */
    image: ImageField;
    /**
     * The width of the image in pixels
     */
    width: number;
    /**
     * The height of the image in pixels
     */
    height: number;
    type: FaceOffOutput.TypeEnum;
    /**
     * The output mask
     */
    mask: ImageField;
    /**
     * The x coordinate of the bounding box\'s left side
     */
    x: number;
    /**
     * The y coordinate of the bounding box\'s top side
     */
    y: number;
}
export namespace FaceOffOutput {
    export type TypeEnum = 'face_off_output';
    export const TypeEnum = {
        FaceOffOutput: 'face_off_output' as TypeEnum
    };
}


