/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { ModelIdentifierField } from './modelIdentifierField';
import { ControlWeight1 } from './controlWeight1';


/**
 * Collect FLUX ControlNet info to pass to other nodes.
 */
export interface FluxControlNetInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    control_model?: ModelIdentifierField | null;
    control_weight?: ControlWeight1;
    /**
     * When the ControlNet is first applied (% of total steps)
     */
    begin_step_percent?: number;
    /**
     * When the ControlNet is last applied (% of total steps)
     */
    end_step_percent?: number;
    /**
     * The resize mode used
     */
    resize_mode?: FluxControlNetInvocation.ResizeModeEnum;
    instantx_control_mode?: number | null;
    type: FluxControlNetInvocation.TypeEnum;
}
export namespace FluxControlNetInvocation {
    export type ResizeModeEnum = 'just_resize' | 'crop_resize' | 'fill_resize' | 'just_resize_simple';
    export const ResizeModeEnum = {
        JustResize: 'just_resize' as ResizeModeEnum,
        CropResize: 'crop_resize' as ResizeModeEnum,
        FillResize: 'fill_resize' as ResizeModeEnum,
        JustResizeSimple: 'just_resize_simple' as ResizeModeEnum
    };
    export type TypeEnum = 'flux_controlnet';
    export const TypeEnum = {
        FluxControlnet: 'flux_controlnet' as TypeEnum
    };
}


