/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelIdentifierField } from './modelIdentifierField';


/**
 * Loads a Flux2 Klein model, outputting its submodels.  Flux2 Klein uses Qwen3 as the text encoder instead of CLIP+T5. It uses a 32-channel VAE (AutoencoderKLFlux2) instead of the 16-channel FLUX.1 VAE.  When using a Diffusers format model, both VAE and Qwen3 encoder are extracted automatically from the main model. You can override with standalone models: - Transformer: Always from Flux2 Klein main model - VAE: From main model (Diffusers) or standalone VAE - Qwen3 Encoder: From main model (Diffusers) or standalone Qwen3 model
 */
export interface Flux2KleinModelLoaderInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    /**
     * Flux model (Transformer) to load
     */
    model: ModelIdentifierField;
    vae_model?: ModelIdentifierField | null;
    qwen3_encoder_model?: ModelIdentifierField | null;
    qwen3_source_model?: ModelIdentifierField | null;
    /**
     * Max sequence length for the Qwen3 encoder.
     */
    max_seq_len?: Flux2KleinModelLoaderInvocation.MaxSeqLenEnum;
    type: Flux2KleinModelLoaderInvocation.TypeEnum;
}
export namespace Flux2KleinModelLoaderInvocation {
    export type MaxSeqLenEnum = 256 | 512;
    export const MaxSeqLenEnum = {
        NUMBER_256: 256 as MaxSeqLenEnum,
        NUMBER_512: 512 as MaxSeqLenEnum
    };
    export type TypeEnum = 'flux2_klein_model_loader';
    export const TypeEnum = {
        Flux2KleinModelLoader: 'flux2_klein_model_loader' as TypeEnum
    };
}


