/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { T5EncoderField } from './t5EncoderField';
import { CLIPField } from './cLIPField';
import { TensorField } from './tensorField';


/**
 * Encodes and preps a prompt for a flux image.
 */
export interface FluxTextEncoderInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    clip?: CLIPField | null;
    t5_encoder?: T5EncoderField | null;
    t5_max_seq_len?: FluxTextEncoderInvocation.T5MaxSeqLenEnum | null;
    prompt?: string | null;
    mask?: TensorField | null;
    type: FluxTextEncoderInvocation.TypeEnum;
}
export namespace FluxTextEncoderInvocation {
    export type T5MaxSeqLenEnum = 256 | 512;
    export const T5MaxSeqLenEnum = {
        NUMBER_256: 256 as T5MaxSeqLenEnum,
        NUMBER_512: 512 as T5MaxSeqLenEnum
    };
    export type TypeEnum = 'flux_text_encoder';
    export const TypeEnum = {
        FluxTextEncoder: 'flux_text_encoder' as TypeEnum
    };
}


