/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DenoiseMaskField } from './denoiseMaskField';
import { FluxConditioningField } from './fluxConditioningField';
import { VAEField } from './vAEField';
import { ReferenceImages } from './referenceImages';
import { LatentsField } from './latentsField';
import { TransformerField } from './transformerField';


/**
 * Run denoising process with a FLUX.2 Klein transformer model.  This node is designed for FLUX.2 Klein models which use Qwen3 as the text encoder. It does not support ControlNet, IP-Adapters, or regional prompting.
 */
export interface Flux2DenoiseInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    latents?: LatentsField | null;
    denoise_mask?: DenoiseMaskField | null;
    /**
     * When to start denoising, expressed a percentage of total steps
     */
    denoising_start?: number;
    /**
     * When to stop denoising, expressed a percentage of total steps
     */
    denoising_end?: number;
    /**
     * Add noise based on denoising start.
     */
    add_noise?: boolean;
    transformer?: TransformerField | null;
    positive_text_conditioning?: FluxConditioningField | null;
    negative_text_conditioning?: FluxConditioningField | null;
    /**
     * Classifier-Free Guidance scale
     */
    cfg_scale?: number;
    /**
     * Width of the generated image.
     */
    width?: number;
    /**
     * Height of the generated image.
     */
    height?: number;
    /**
     * Number of diffusion steps. Use 4 for distilled models, 28+ for base models.
     */
    num_steps?: number;
    /**
     * Scheduler (sampler) for the denoising process. \'euler\' is fast and standard. \'heun\' is 2nd-order (better quality, 2x slower). \'lcm\' is optimized for few steps.
     */
    scheduler?: Flux2DenoiseInvocation.SchedulerEnum;
    /**
     * Randomness seed for reproducibility.
     */
    seed?: number;
    vae?: VAEField | null;
    kontext_conditioning?: ReferenceImages | null;
    type: Flux2DenoiseInvocation.TypeEnum;
}
export namespace Flux2DenoiseInvocation {
    export type SchedulerEnum = 'euler' | 'heun' | 'lcm';
    export const SchedulerEnum = {
        Euler: 'euler' as SchedulerEnum,
        Heun: 'heun' as SchedulerEnum,
        Lcm: 'lcm' as SchedulerEnum
    };
    export type TypeEnum = 'flux2_denoise';
    export const TypeEnum = {
        Flux2Denoise: 'flux2_denoise' as TypeEnum
    };
}


