/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { T5EncoderField } from './t5EncoderField';
import { CLIPField } from './cLIPField';
import { VAEField } from './vAEField';
import { TransformerField } from './transformerField';


/**
 * Flux base model loader output
 */
export interface FluxModelLoaderOutput { 
    /**
     * Transformer
     */
    transformer: TransformerField;
    /**
     * CLIP (tokenizer, text encoder, LoRAs) and skipped layer count
     */
    clip: CLIPField;
    /**
     * T5 tokenizer and text encoder
     */
    t5_encoder: T5EncoderField;
    /**
     * VAE
     */
    vae: VAEField;
    /**
     * The max sequence length to used for the T5 encoder. (256 for schnell transformer, 512 for dev transformer)
     */
    max_seq_len: FluxModelLoaderOutput.MaxSeqLenEnum;
    type: FluxModelLoaderOutput.TypeEnum;
}
export namespace FluxModelLoaderOutput {
    export type MaxSeqLenEnum = 256 | 512;
    export const MaxSeqLenEnum = {
        NUMBER_256: 256 as MaxSeqLenEnum,
        NUMBER_512: 512 as MaxSeqLenEnum
    };
    export type TypeEnum = 'flux_model_loader_output';
    export const TypeEnum = {
        FluxModelLoaderOutput: 'flux_model_loader_output' as TypeEnum
    };
}


