/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransformerField } from './transformerField';
import { Qwen3EncoderField } from './qwen3EncoderField';


/**
 * FLUX.2 Klein LoRA Loader Output
 */
export interface Flux2KleinLoRALoaderOutput { 
    transformer: TransformerField | null;
    qwen3_encoder: Qwen3EncoderField | null;
    type: Flux2KleinLoRALoaderOutput.TypeEnum;
}
export namespace Flux2KleinLoRALoaderOutput {
    export type TypeEnum = 'flux2_klein_lora_loader_output';
    export const TypeEnum = {
        Flux2KleinLoraLoaderOutput: 'flux2_klein_lora_loader_output' as TypeEnum
    };
}


