/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoRAs } from './loRAs';
import { TransformerField } from './transformerField';
import { Qwen3EncoderField } from './qwen3EncoderField';


/**
 * Applies a collection of LoRAs to a FLUX.2 Klein transformer and/or Qwen3 text encoder.
 */
export interface Flux2KleinLoRACollectionLoader { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    loras?: LoRAs | null;
    transformer?: TransformerField | null;
    qwen3_encoder?: Qwen3EncoderField | null;
    type: Flux2KleinLoRACollectionLoader.TypeEnum;
}
export namespace Flux2KleinLoRACollectionLoader {
    export type TypeEnum = 'flux2_klein_lora_collection_loader';
    export const TypeEnum = {
        Flux2KleinLoraCollectionLoader: 'flux2_klein_lora_collection_loader' as TypeEnum
    };
}


