/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Prepares an image or images for use with FLUX Kontext. The first/single image is resized to the nearest preferred Kontext resolution. All other images are concatenated horizontally, maintaining their aspect ratio.
 */
export interface FluxKontextConcatenateImagesInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    images?: Array<ImageField> | null;
    /**
     * Use FLUX preferred resolutions for the first image
     */
    use_preferred_resolution?: boolean;
    type: FluxKontextConcatenateImagesInvocation.TypeEnum;
}
export namespace FluxKontextConcatenateImagesInvocation {
    export type TypeEnum = 'flux_kontext_image_prep';
    export const TypeEnum = {
        FluxKontextImagePrep: 'flux_kontext_image_prep' as TypeEnum
    };
}


