/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TensorField } from './tensorField';
import { Qwen3EncoderField } from './qwen3EncoderField';


/**
 * Encodes and preps a prompt for Flux2 Klein image generation.  Flux2 Klein uses Qwen3 as the text encoder, extracting hidden states from layers (9, 18, 27) and stacking them for richer text representations. This matches the diffusers Flux2KleinPipeline implementation exactly.
 */
export interface Flux2KleinTextEncoderInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    prompt?: string | null;
    qwen3_encoder?: Qwen3EncoderField | null;
    /**
     * Max sequence length for the Qwen3 encoder.
     */
    max_seq_len?: Flux2KleinTextEncoderInvocation.MaxSeqLenEnum;
    mask?: TensorField | null;
    type: Flux2KleinTextEncoderInvocation.TypeEnum;
}
export namespace Flux2KleinTextEncoderInvocation {
    export type MaxSeqLenEnum = 256 | 512;
    export const MaxSeqLenEnum = {
        NUMBER_256: 256 as MaxSeqLenEnum,
        NUMBER_512: 512 as MaxSeqLenEnum
    };
    export type TypeEnum = 'flux2_klein_text_encoder';
    export const TypeEnum = {
        Flux2KleinTextEncoder: 'flux2_klein_text_encoder' as TypeEnum
    };
}


