/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { VAEField } from './vAEField';


/**
 * Encodes an image into latents using FLUX.2 Klein\'s 32-channel VAE.
 */
export interface Flux2VaeEncodeInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    vae?: VAEField | null;
    type: Flux2VaeEncodeInvocation.TypeEnum;
}
export namespace Flux2VaeEncodeInvocation {
    export type TypeEnum = 'flux2_vae_encode';
    export const TypeEnum = {
        Flux2VaeEncode: 'flux2_vae_encode' as TypeEnum
    };
}


