/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { TensorField } from './tensorField';


/**
 * Prepare the FLUX Fill conditioning data.
 */
export interface FluxFillInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    mask?: TensorField | null;
    type: FluxFillInvocation.TypeEnum;
}
export namespace FluxFillInvocation {
    export type TypeEnum = 'flux_fill';
    export const TypeEnum = {
        FluxFill: 'flux_fill' as TypeEnum
    };
}


