/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { T5EncoderField } from './t5EncoderField';
import { CLIPField } from './cLIPField';
import { TransformerField } from './transformerField';


/**
 * FLUX LoRA Loader Output
 */
export interface FluxLoRALoaderOutput { 
    transformer: TransformerField | null;
    clip: CLIPField | null;
    t5_encoder: T5EncoderField | null;
    type: FluxLoRALoaderOutput.TypeEnum;
}
export namespace FluxLoRALoaderOutput {
    export type TypeEnum = 'flux_lora_loader_output';
    export const TypeEnum = {
        FluxLoraLoaderOutput: 'flux_lora_loader_output' as TypeEnum
    };
}


