/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DenoiseMaskField } from './denoiseMaskField';
import { VAEField } from './vAEField';
import { PositiveTextConditioning } from './positiveTextConditioning';
import { ControlLoRAField } from './controlLoRAField';
import { NegativeTextConditioning } from './negativeTextConditioning';
import { TransformerField } from './transformerField';
import { CFGScale2 } from './cFGScale2';
import { ReduxConditioning } from './reduxConditioning';
import { KontextConditioning } from './kontextConditioning';
import { LatentsField } from './latentsField';
import { Control1 } from './control1';
import { FluxFillConditioningField } from './fluxFillConditioningField';
import { IPAdapter1 } from './iPAdapter1';


/**
 * Run denoising process with a FLUX transformer model + metadata.
 */
export interface FluxDenoiseLatentsMetaInvocation { 
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    latents?: LatentsField | null;
    denoise_mask?: DenoiseMaskField | null;
    /**
     * When to start denoising, expressed a percentage of total steps
     */
    denoising_start?: number;
    /**
     * When to stop denoising, expressed a percentage of total steps
     */
    denoising_end?: number;
    /**
     * Add noise based on denoising start.
     */
    add_noise?: boolean;
    transformer?: TransformerField | null;
    control_lora?: ControlLoRAField | null;
    positive_text_conditioning?: PositiveTextConditioning | null;
    negative_text_conditioning?: NegativeTextConditioning | null;
    redux_conditioning?: ReduxConditioning | null;
    fill_conditioning?: FluxFillConditioningField | null;
    cfg_scale?: CFGScale2;
    /**
     * Index of the first step to apply cfg_scale. Negative indices count backwards from the the last step (e.g. a value of -1 refers to the final step).
     */
    cfg_scale_start_step?: number;
    /**
     * Index of the last step to apply cfg_scale. Negative indices count backwards from the last step (e.g. a value of -1 refers to the final step).
     */
    cfg_scale_end_step?: number;
    /**
     * Width of the generated image.
     */
    width?: number;
    /**
     * Height of the generated image.
     */
    height?: number;
    /**
     * Number of diffusion steps. Recommended values are schnell: 4, dev: 50.
     */
    num_steps?: number;
    /**
     * Scheduler (sampler) for the denoising process. \'euler\' is fast and standard. \'heun\' is 2nd-order (better quality, 2x slower). \'lcm\' is optimized for few steps.
     */
    scheduler?: FluxDenoiseLatentsMetaInvocation.SchedulerEnum;
    /**
     * The guidance strength. Higher values adhere more strictly to the prompt, and will produce less diverse images. FLUX dev only, ignored for schnell.
     */
    guidance?: number;
    /**
     * Randomness seed for reproducibility.
     */
    seed?: number;
    control?: Control1 | null;
    controlnet_vae?: VAEField | null;
    ip_adapter?: IPAdapter1 | null;
    kontext_conditioning?: KontextConditioning | null;
    /**
     * DyPE preset for high-resolution generation. \'auto\' enables automatically for resolutions > 1536px. \'area\' enables automatically based on image area. \'4k\' uses optimized settings for 4K output.
     */
    dype_preset?: FluxDenoiseLatentsMetaInvocation.DypePresetEnum;
    dype_scale?: number | null;
    dype_exponent?: number | null;
    type: FluxDenoiseLatentsMetaInvocation.TypeEnum;
}
export namespace FluxDenoiseLatentsMetaInvocation {
    export type SchedulerEnum = 'euler' | 'heun' | 'lcm';
    export const SchedulerEnum = {
        Euler: 'euler' as SchedulerEnum,
        Heun: 'heun' as SchedulerEnum,
        Lcm: 'lcm' as SchedulerEnum
    };
    export type DypePresetEnum = 'off' | 'manual' | 'auto' | 'area' | '4k';
    export const DypePresetEnum = {
        Off: 'off' as DypePresetEnum,
        Manual: 'manual' as DypePresetEnum,
        Auto: 'auto' as DypePresetEnum,
        Area: 'area' as DypePresetEnum,
        _4k: '4k' as DypePresetEnum
    };
    export type TypeEnum = 'flux_denoise_meta';
    export const TypeEnum = {
        FluxDenoiseMeta: 'flux_denoise_meta' as TypeEnum
    };
}


