/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TensorField } from './tensorField';


/**
 * A FLUX Redux conditioning tensor primitive value
 */
export interface FluxReduxConditioningField { 
    /**
     * The Redux image conditioning tensor.
     */
    conditioning: TensorField;
    mask?: TensorField | null;
}

