/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { VAEField } from './vAEField';


/**
 * Encodes an image into latents.
 */
export interface FluxVaeEncodeInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    vae?: VAEField | null;
    type: FluxVaeEncodeInvocation.TypeEnum;
}
export namespace FluxVaeEncodeInvocation {
    export type TypeEnum = 'flux_vae_encode';
    export const TypeEnum = {
        FluxVaeEncode: 'flux_vae_encode' as TypeEnum
    };
}


