/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FluxFillConditioningField } from './fluxFillConditioningField';


/**
 * The conditioning output of a FLUX Fill invocation.
 */
export interface FluxFillOutput { 
    /**
     * FLUX Redux conditioning tensor
     */
    fill_cond: FluxFillConditioningField;
    type: FluxFillOutput.TypeEnum;
}
export namespace FluxFillOutput {
    export type TypeEnum = 'flux_fill_output';
    export const TypeEnum = {
        FluxFillOutput: 'flux_fill_output' as TypeEnum
    };
}


