/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { TensorField } from './tensorField';


/**
 * A FLUX Fill conditioning field.
 */
export interface FluxFillConditioningField { 
    /**
     * The FLUX Fill reference image.
     */
    image: ImageField;
    /**
     * The FLUX Fill inpaint mask.
     */
    mask: TensorField;
}

