/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { ColorField } from './colorField';


/**
 * Gets the bounding box of the given mask image.
 */
export interface GetMaskBoundingBoxInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    mask?: ImageField | null;
    /**
     * Margin to add to the bounding box.
     */
    margin?: number;
    /**
     * Color of the mask in the image.
     */
    mask_color?: ColorField;
    type: GetMaskBoundingBoxInvocation.TypeEnum;
}
export namespace GetMaskBoundingBoxInvocation {
    export type TypeEnum = 'get_image_mask_bounding_box';
    export const TypeEnum = {
        GetImageMaskBoundingBox: 'get_image_mask_bounding_box' as TypeEnum
    };
}


