/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Graph } from './graph';
import { ResultsValue } from './resultsValue';


/**
 * Tracks the state of a graph execution
 */
export interface GraphExecutionState { 
    /**
     * The id of the execution state
     */
    id: string;
    /**
     * The graph being executed
     */
    graph: Graph;
    /**
     * The expanded graph of activated and executed nodes
     */
    execution_graph: Graph;
    /**
     * The set of node ids that have been executed
     */
    executed: Set<string>;
    /**
     * The list of node ids that have been executed, in order of execution
     */
    executed_history: Array<string>;
    /**
     * The results of node executions
     */
    results: { [key: string]: ResultsValue; };
    /**
     * Errors raised when executing nodes
     */
    errors: { [key: string]: string; };
    /**
     * The map of prepared nodes to original graph nodes
     */
    prepared_source_mapping: { [key: string]: string; };
    /**
     * The map of original graph nodes to prepared nodes
     */
    source_prepared_mapping: { [key: string]: Set<string>; };
    ready_order?: Array<string>;
    /**
     * Remaining unmet input count for exec nodes
     */
    indegree?: { [key: string]: number; };
}

