/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';


/**
 * Runs a Grounding DINO model. Performs zero-shot bounding-box object detection from a text prompt.
 */
export interface GroundingDinoInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    model?: GroundingDinoInvocation.ModelEnum | null;
    prompt?: string | null;
    image?: ImageField | null;
    /**
     * The detection threshold for the Grounding DINO model. All detected bounding boxes with scores above this threshold will be returned.
     */
    detection_threshold?: number;
    type: GroundingDinoInvocation.TypeEnum;
}
export namespace GroundingDinoInvocation {
    export type ModelEnum = 'grounding-dino-tiny' | 'grounding-dino-base';
    export const ModelEnum = {
        GroundingDinoTiny: 'grounding-dino-tiny' as ModelEnum,
        GroundingDinoBase: 'grounding-dino-base' as ModelEnum
    };
    export type TypeEnum = 'grounding_dino';
    export const TypeEnum = {
        GroundingDino: 'grounding_dino' as TypeEnum
    };
}


