/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';


/**
 * Resize an image using a heuristic method. Preserves edge maps.
 */
export interface HeuristicResizeInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    /**
     * The width to resize to (px)
     */
    width?: number;
    /**
     * The height to resize to (px)
     */
    height?: number;
    type: HeuristicResizeInvocation.TypeEnum;
}
export namespace HeuristicResizeInvocation {
    export type TypeEnum = 'heuristic_resize';
    export const TypeEnum = {
        HeuristicResize: 'heuristic_resize' as TypeEnum
    };
}


