/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelRepoVariant } from './modelRepoVariant';


/**
 * A HuggingFace repo_id with optional variant, sub-folder(s) and access token. Note that the variant option, if not provided to the constructor, will default to fp16, which is what people (almost) always want.  The subfolder can be a single path or multiple paths joined by \'+\' (e.g., \"text_encoder+tokenizer\"). When multiple subfolders are specified, all of them will be downloaded and combined into the model directory.
 */
export interface HFModelSource { 
    repo_id: string;
    variant?: ModelRepoVariant | null;
    subfolder?: string | null;
    access_token?: string | null;
    type?: HFModelSource.TypeEnum;
}
export namespace HFModelSource {
    export type TypeEnum = 'hf';
    export const TypeEnum = {
        Hf: 'hf' as TypeEnum
    };
}


