/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RemoteModelFile } from './remoteModelFile';


/**
 * Extended metadata fields provided by HuggingFace.
 */
export interface HuggingFaceMetadata { 
    /**
     * model\'s name
     */
    name: string;
    /**
     * model files and their sizes
     */
    files?: Array<RemoteModelFile>;
    type?: HuggingFaceMetadata.TypeEnum;
    /**
     * The HF model id
     */
    id: string;
    api_response?: string | null;
    /**
     * Whether the metadata is for a Diffusers format model
     */
    is_diffusers?: boolean;
    ckpt_urls?: Array<string> | null;
}
export namespace HuggingFaceMetadata {
    export type TypeEnum = 'huggingface';
    export const TypeEnum = {
        Huggingface: 'huggingface' as TypeEnum
    };
}


