/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The category of an image.  - GENERAL: The image is an output, init image, or otherwise an image without a specialized purpose. - MASK: The image is a mask image. - CONTROL: The image is a ControlNet control image. - USER: The image is a user-provide image. - OTHER: The image is some other type of image with a specialized purpose. To be used by external nodes.
 */
export type ImageCategory = 'general' | 'mask' | 'control' | 'user' | 'other';

export const ImageCategory = {
    General: 'general' as ImageCategory,
    Mask: 'mask' as ImageCategory,
    Control: 'control' as ImageCategory,
    User: 'user' as ImageCategory,
    Other: 'other' as ImageCategory
};

