/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { VAEField } from './vAEField';


/**
 * Encodes an image into latents.
 */
export interface ImageToLatentsInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    vae?: VAEField | null;
    /**
     * Processing using overlapping tiles (reduce memory consumption)
     */
    tiled?: boolean;
    /**
     * The tile size for VAE tiling in pixels (image space). If set to 0, the default tile size for the model will be used. Larger tile sizes generally produce better results at the cost of higher memory usage.
     */
    tile_size?: number;
    /**
     * Whether or not to use full float32 precision
     */
    fp32?: boolean;
    /**
     * Apply VAE scaling compensation when encoding images (reduces color drift).
     */
    color_compensation?: ImageToLatentsInvocation.ColorCompensationEnum;
    type: ImageToLatentsInvocation.TypeEnum;
}
export namespace ImageToLatentsInvocation {
    export type ColorCompensationEnum = 'None' | 'SDXL';
    export const ColorCompensationEnum = {
        None: 'None' as ColorCompensationEnum,
        Sdxl: 'SDXL' as ColorCompensationEnum
    };
    export type TypeEnum = 'i2l';
    export const TypeEnum = {
        I2l: 'i2l' as TypeEnum
    };
}


