/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';


/**
 * Base class for nodes that output a collection of images
 */
export interface ImageCollectionOutput { 
    /**
     * The output images
     */
    collection: Array<ImageField>;
    type: ImageCollectionOutput.TypeEnum;
}
export namespace ImageCollectionOutput {
    export type TypeEnum = 'image_collection_output';
    export const TypeEnum = {
        ImageCollectionOutput: 'image_collection_output' as TypeEnum
    };
}


