/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';


/**
 * Base class for nodes that output a single image
 */
export interface ImageOutput { 
    /**
     * The output image
     */
    image: ImageField;
    /**
     * The width of the image in pixels
     */
    width: number;
    /**
     * The height of the image in pixels
     */
    height: number;
    type: ImageOutput.TypeEnum;
}
export namespace ImageOutput {
    export type TypeEnum = 'image_output';
    export const TypeEnum = {
        ImageOutput: 'image_output' as TypeEnum
    };
}


