/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Converts an image to a different mode.
 */
export interface ImageConvertInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    /**
     * The mode to convert to
     */
    mode?: ImageConvertInvocation.ModeEnum;
    type: ImageConvertInvocation.TypeEnum;
}
export namespace ImageConvertInvocation {
    export type ModeEnum = 'L' | 'RGB' | 'RGBA' | 'CMYK' | 'YCbCr' | 'LAB' | 'HSV' | 'I' | 'F';
    export const ModeEnum = {
        L: 'L' as ModeEnum,
        Rgb: 'RGB' as ModeEnum,
        Rgba: 'RGBA' as ModeEnum,
        Cmyk: 'CMYK' as ModeEnum,
        YcbCr: 'YCbCr' as ModeEnum,
        Lab: 'LAB' as ModeEnum,
        Hsv: 'HSV' as ModeEnum,
        I: 'I' as ModeEnum,
        F: 'F' as ModeEnum
    };
    export type TypeEnum = 'img_conv';
    export const TypeEnum = {
        ImgConv: 'img_conv' as TypeEnum
    };
}


