/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Gets a channel from an image.
 */
export interface ImageChannelInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    /**
     * The channel to get
     */
    channel?: ImageChannelInvocation.ChannelEnum;
    type: ImageChannelInvocation.TypeEnum;
}
export namespace ImageChannelInvocation {
    export type ChannelEnum = 'A' | 'R' | 'G' | 'B';
    export const ChannelEnum = {
        A: 'A' as ChannelEnum,
        R: 'R' as ChannelEnum,
        G: 'G' as ChannelEnum,
        B: 'B' as ChannelEnum
    };
    export type TypeEnum = 'img_chan';
    export const TypeEnum = {
        ImgChan: 'img_chan' as TypeEnum
    };
}


