/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Add or subtract a value from a specific color channel of an image.
 */
export interface ImageChannelOffsetInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    channel?: ImageChannelOffsetInvocation.ChannelEnum | null;
    /**
     * The amount to adjust the channel by
     */
    offset?: number;
    type: ImageChannelOffsetInvocation.TypeEnum;
}
export namespace ImageChannelOffsetInvocation {
    export type ChannelEnum = 'Red (RGBA)' | 'Green (RGBA)' | 'Blue (RGBA)' | 'Alpha (RGBA)' | 'Cyan (CMYK)' | 'Magenta (CMYK)' | 'Yellow (CMYK)' | 'Black (CMYK)' | 'Hue (HSV)' | 'Saturation (HSV)' | 'Value (HSV)' | 'Luminosity (LAB)' | 'A (LAB)' | 'B (LAB)' | 'Y (YCbCr)' | 'Cb (YCbCr)' | 'Cr (YCbCr)';
    export const ChannelEnum = {
        RedRgba: 'Red (RGBA)' as ChannelEnum,
        GreenRgba: 'Green (RGBA)' as ChannelEnum,
        BlueRgba: 'Blue (RGBA)' as ChannelEnum,
        AlphaRgba: 'Alpha (RGBA)' as ChannelEnum,
        CyanCmyk: 'Cyan (CMYK)' as ChannelEnum,
        MagentaCmyk: 'Magenta (CMYK)' as ChannelEnum,
        YellowCmyk: 'Yellow (CMYK)' as ChannelEnum,
        BlackCmyk: 'Black (CMYK)' as ChannelEnum,
        HueHsv: 'Hue (HSV)' as ChannelEnum,
        SaturationHsv: 'Saturation (HSV)' as ChannelEnum,
        ValueHsv: 'Value (HSV)' as ChannelEnum,
        LuminosityLab: 'Luminosity (LAB)' as ChannelEnum,
        ALab: 'A (LAB)' as ChannelEnum,
        BLab: 'B (LAB)' as ChannelEnum,
        YYcbCr: 'Y (YCbCr)' as ChannelEnum,
        CbYcbCr: 'Cb (YCbCr)' as ChannelEnum,
        CrYcbCr: 'Cr (YCbCr)' as ChannelEnum
    };
    export type TypeEnum = 'img_channel_offset';
    export const TypeEnum = {
        ImgChannelOffset: 'img_channel_offset' as TypeEnum
    };
}


