/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageDTO } from './imageDTO';


export interface ImageUploadEntry { 
    /**
     * The image DTO
     */
    image_dto: ImageDTO;
    /**
     * The URL to get the presigned URL for the image upload
     */
    presigned_url: string;
}

