/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Infills transparent areas of an image using the PatchMatch algorithm
 */
export interface InfillPatchMatchInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    /**
     * Run patchmatch on downscaled image to speedup infill
     */
    downscale?: number;
    /**
     * The resampling mode
     */
    resample_mode?: InfillPatchMatchInvocation.ResampleModeEnum;
    type: InfillPatchMatchInvocation.TypeEnum;
}
export namespace InfillPatchMatchInvocation {
    export type ResampleModeEnum = 'nearest' | 'box' | 'bilinear' | 'hamming' | 'bicubic' | 'lanczos';
    export const ResampleModeEnum = {
        Nearest: 'nearest' as ResampleModeEnum,
        Box: 'box' as ResampleModeEnum,
        Bilinear: 'bilinear' as ResampleModeEnum,
        Hamming: 'hamming' as ResampleModeEnum,
        Bicubic: 'bicubic' as ResampleModeEnum,
        Lanczos: 'lanczos' as ResampleModeEnum
    };
    export type TypeEnum = 'infill_patchmatch';
    export const TypeEnum = {
        InfillPatchmatch: 'infill_patchmatch' as TypeEnum
    };
}


