/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';
import { ColorField } from './colorField';


/**
 * Infills transparent areas of an image with a solid color
 */
export interface InfillColorInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    /**
     * The color to use to infill
     */
    color?: ColorField;
    type: InfillColorInvocation.TypeEnum;
}
export namespace InfillColorInvocation {
    export type TypeEnum = 'infill_rgba';
    export const TypeEnum = {
        InfillRgba: 'infill_rgba' as TypeEnum
    };
}


