/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Generated a range of integers for use in a batched generation
 */
export interface IntegerGenerator { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    /**
     * The integer generator.
     */
    generator: object;
    type: IntegerGenerator.TypeEnum;
}
export namespace IntegerGenerator {
    export type TypeEnum = 'integer_generator';
    export const TypeEnum = {
        IntegerGenerator: 'integer_generator' as TypeEnum
    };
}


