/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Performs integer math.
 */
export interface IntegerMathInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    /**
     * The operation to perform
     */
    operation?: IntegerMathInvocation.OperationEnum;
    /**
     * The first number
     */
    a?: number;
    /**
     * The second number
     */
    b?: number;
    type: IntegerMathInvocation.TypeEnum;
}
export namespace IntegerMathInvocation {
    export type OperationEnum = 'ADD' | 'SUB' | 'MUL' | 'DIV' | 'EXP' | 'MOD' | 'ABS' | 'MIN' | 'MAX';
    export const OperationEnum = {
        Add: 'ADD' as OperationEnum,
        Sub: 'SUB' as OperationEnum,
        Mul: 'MUL' as OperationEnum,
        Div: 'DIV' as OperationEnum,
        Exp: 'EXP' as OperationEnum,
        Mod: 'MOD' as OperationEnum,
        Abs: 'ABS' as OperationEnum,
        Min: 'MIN' as OperationEnum,
        Max: 'MAX' as OperationEnum
    };
    export type TypeEnum = 'integer_math';
    export const TypeEnum = {
        IntegerMath: 'integer_math' as TypeEnum
    };
}


