/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TensorField } from './tensorField';


/**
 * Inverts a tensor mask.
 */
export interface InvertTensorMaskInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    mask?: TensorField | null;
    type: InvertTensorMaskInvocation.TypeEnum;
}
export namespace InvertTensorMaskInvocation {
    export type TypeEnum = 'invert_tensor_mask';
    export const TypeEnum = {
        InvertTensorMask: 'invert_tensor_mask' as TypeEnum
    };
}


