/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Applies processing from PIL\'s ImageEnhance module. Originally created by @dwringer
 */
export interface InvokeImageEnhanceInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    /**
     * Whether to invert the image colors
     */
    invert?: boolean;
    /**
     * Color enhancement factor
     */
    color?: number;
    /**
     * Contrast enhancement factor
     */
    contrast?: number;
    /**
     * Brightness enhancement factor
     */
    brightness?: number;
    /**
     * Sharpness enhancement factor
     */
    sharpness?: number;
    type: InvokeImageEnhanceInvocation.TypeEnum;
}
export namespace InvokeImageEnhanceInvocation {
    export type TypeEnum = 'invokeai_img_enhance';
    export const TypeEnum = {
        InvokeaiImgEnhance: 'invokeai_img_enhance' as TypeEnum
    };
}


