/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';


/**
 * Dilate (expand) or erode (contract) an image. Originally created by @dwringer
 */
export interface InvokeImageDilateOrErodeInvocation { 
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    /**
     * If true, only applies to image lightness (CIELa*b*)
     */
    lightness_only?: boolean;
    /**
     * Width (in pixels) by which to dilate(expand) or erode (contract) the image
     */
    radius_w?: number;
    /**
     * Height (in pixels) by which to dilate(expand) or erode (contract) the image
     */
    radius_h?: number;
    /**
     * How to operate on the image
     */
    mode?: InvokeImageDilateOrErodeInvocation.ModeEnum;
    type: InvokeImageDilateOrErodeInvocation.TypeEnum;
}
export namespace InvokeImageDilateOrErodeInvocation {
    export type ModeEnum = 'Dilate' | 'Erode';
    export const ModeEnum = {
        Dilate: 'Dilate' as ModeEnum,
        Erode: 'Erode' as ModeEnum
    };
    export type TypeEnum = 'invokeai_img_dilate_erode';
    export const TypeEnum = {
        InvokeaiImgDilateErode: 'invokeai_img_dilate_erode' as TypeEnum
    };
}


