/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Clip image to pure black/white past specified thresholds. Originally created by @dwringer
 */
export interface InvokeImageValueThresholdsInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    /**
     * Make light areas dark and vice versa
     */
    invert_output?: boolean;
    /**
     * Rescale remaining values from minimum to maximum
     */
    renormalize_values?: boolean;
    /**
     * If true, only applies to image lightness (CIELa*b*)
     */
    lightness_only?: boolean;
    /**
     * Threshold above which will be set to full value
     */
    threshold_upper?: number;
    /**
     * Threshold below which will be set to minimum value
     */
    threshold_lower?: number;
    type: InvokeImageValueThresholdsInvocation.TypeEnum;
}
export namespace InvokeImageValueThresholdsInvocation {
    export type TypeEnum = 'invokeai_img_val_thresholds';
    export const TypeEnum = {
        InvokeaiImgValThresholds: 'invokeai_img_val_thresholds' as TypeEnum
    };
}


