/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelSourceType } from './modelSourceType';


export interface IPAdapterCheckpointSD1Config { 
    /**
     * A unique key for this model.
     */
    key: string;
    /**
     * The hash of the model file(s).
     */
    hash: string;
    /**
     * Path to the model on the filesystem. Relative paths are relative to the Invoke root directory.
     */
    path: string;
    /**
     * The size of the model in bytes.
     */
    file_size: number;
    /**
     * Name of the model.
     */
    name: string;
    description: string | null;
    /**
     * The original source of the model (path, URL or repo_id).
     */
    source: string;
    /**
     * The type of source
     */
    source_type: ModelSourceType;
    source_api_response: string | null;
    cover_image: string | null;
    type: IPAdapterCheckpointSD1Config.TypeEnum;
    format: IPAdapterCheckpointSD1Config.FormatEnum;
    base: IPAdapterCheckpointSD1Config.BaseEnum;
}
export namespace IPAdapterCheckpointSD1Config {
    export type TypeEnum = 'ip_adapter';
    export const TypeEnum = {
        IpAdapter: 'ip_adapter' as TypeEnum
    };
    export type FormatEnum = 'checkpoint';
    export const FormatEnum = {
        Checkpoint: 'checkpoint' as FormatEnum
    };
    export type BaseEnum = 'sd-1';
    export const BaseEnum = {
        Sd1: 'sd-1' as BaseEnum
    };
}


