/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response containing ordered item ids with metadata for optimistic updates.
 */
export interface ItemIdsResult { 
    /**
     * Ordered list of item ids
     */
    item_ids: Array<number>;
    /**
     * Total number of queue items matching the query
     */
    total_count: number;
}

