/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Iterates over a list of items
 */
export interface IterateInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    /**
     * The list of items to iterate over
     */
    collection?: Array<any>;
    /**
     * The index, will be provided on executed iterators
     */
    index?: number;
    type: IterateInvocation.TypeEnum;
}
export namespace IterateInvocation {
    export type TypeEnum = 'iterate';
    export const TypeEnum = {
        Iterate: 'iterate' as TypeEnum
    };
}


