/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LatentsField } from './latentsField';


/**
 * Base class for nodes that output a collection of latents tensors
 */
export interface LatentsCollectionOutput { 
    /**
     * Latents tensor
     */
    collection: Array<LatentsField>;
    type: LatentsCollectionOutput.TypeEnum;
}
export namespace LatentsCollectionOutput {
    export type TypeEnum = 'latents_collection_output';
    export const TypeEnum = {
        LatentsCollectionOutput: 'latents_collection_output' as TypeEnum
    };
}


