/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LatentsField } from './latentsField';


/**
 * A latents tensor primitive value
 */
export interface LatentsInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    latents?: LatentsField | null;
    type: LatentsInvocation.TypeEnum;
}
export namespace LatentsInvocation {
    export type TypeEnum = 'latents';
    export const TypeEnum = {
        Latents: 'latents' as TypeEnum
    };
}


