/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A latents tensor primitive field
 */
export interface LatentsField { 
    /**
     * The name of the latents
     */
    latents_name: string;
    seed?: number | null;
}

