/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelIdentifierField } from './modelIdentifierField';
import { LlavaOnevisionVllmInvocationImages } from './llavaOnevisionVllmInvocationImages';


/**
 * Run a LLaVA OneVision VLLM model.
 */
export interface LlavaOnevisionVllmInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    images?: LlavaOnevisionVllmInvocationImages | null;
    /**
     * Input text prompt.
     */
    prompt?: string;
    vllm_model?: ModelIdentifierField | null;
    type: LlavaOnevisionVllmInvocation.TypeEnum;
}
export namespace LlavaOnevisionVllmInvocation {
    export type TypeEnum = 'llava_onevision_vllm';
    export const TypeEnum = {
        LlavaOnevisionVllm: 'llava_onevision_vllm' as TypeEnum
    };
}


