/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelSourceType } from './modelSourceType';
import { ModelRepoVariant } from './modelRepoVariant';


/**
 * Model config for Llava Onevision models.
 */
export interface LlavaOnevisionDiffusersConfig { 
    /**
     * A unique key for this model.
     */
    key: string;
    /**
     * The hash of the model file(s).
     */
    hash: string;
    /**
     * Path to the model on the filesystem. Relative paths are relative to the Invoke root directory.
     */
    path: string;
    /**
     * The size of the model in bytes.
     */
    file_size: number;
    /**
     * Name of the model.
     */
    name: string;
    description: string | null;
    /**
     * The original source of the model (path, URL or repo_id).
     */
    source: string;
    /**
     * The type of source
     */
    source_type: ModelSourceType;
    source_api_response: string | null;
    cover_image: string | null;
    format: LlavaOnevisionDiffusersConfig.FormatEnum;
    repo_variant: ModelRepoVariant;
    type: LlavaOnevisionDiffusersConfig.TypeEnum;
    base: LlavaOnevisionDiffusersConfig.BaseEnum;
    cpu_only: boolean | null;
}
export namespace LlavaOnevisionDiffusersConfig {
    export type FormatEnum = 'diffusers';
    export const FormatEnum = {
        Diffusers: 'diffusers' as FormatEnum
    };
    export type TypeEnum = 'llava_onevision';
    export const TypeEnum = {
        LlavaOnevision: 'llava_onevision' as TypeEnum
    };
    export type BaseEnum = 'any';
    export const BaseEnum = {
        Any: 'any' as BaseEnum
    };
}


