/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request body for user login.
 */
export interface LoginRequest { 
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
    /**
     * Whether to extend session duration
     */
    remember_me?: boolean;
}

