/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CLIPField } from './cLIPField';
import { LoRAs } from './loRAs';
import { UNetField } from './uNetField';


/**
 * Applies a collection of LoRAs to the provided UNet and CLIP models.
 */
export interface LoRACollectionLoader { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    loras?: LoRAs | null;
    unet?: UNetField | null;
    clip?: CLIPField | null;
    type: LoRACollectionLoader.TypeEnum;
}
export namespace LoRACollectionLoader {
    export type TypeEnum = 'lora_collection_loader';
    export const TypeEnum = {
        LoraCollectionLoader: 'lora_collection_loader' as TypeEnum
    };
}


