/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelIdentifierField } from './modelIdentifierField';


/**
 * Selects a LoRA model and weight.
 */
export interface LoRASelectorInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    lora?: ModelIdentifierField | null;
    /**
     * The weight at which the LoRA is applied to each model
     */
    weight?: number;
    type: LoRASelectorInvocation.TypeEnum;
}
export namespace LoRASelectorInvocation {
    export type TypeEnum = 'lora_selector';
    export const TypeEnum = {
        LoraSelector: 'lora_selector' as TypeEnum
    };
}


