/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelSourceType } from './modelSourceType';
import { ZImageVariantType } from './zImageVariantType';
import { LoraModelDefaultSettings } from './loraModelDefaultSettings';


/**
 * Model config for Z-Image LoRA models in LyCORIS format.
 */
export interface LoRALyCORISZImageConfig { 
    /**
     * A unique key for this model.
     */
    key: string;
    /**
     * The hash of the model file(s).
     */
    hash: string;
    /**
     * Path to the model on the filesystem. Relative paths are relative to the Invoke root directory.
     */
    path: string;
    /**
     * The size of the model in bytes.
     */
    file_size: number;
    /**
     * Name of the model.
     */
    name: string;
    description: string | null;
    /**
     * The original source of the model (path, URL or repo_id).
     */
    source: string;
    /**
     * The type of source
     */
    source_type: ModelSourceType;
    source_api_response: string | null;
    cover_image: string | null;
    type: LoRALyCORISZImageConfig.TypeEnum;
    trigger_phrases: Set<string> | null;
    default_settings: LoraModelDefaultSettings | null;
    format: LoRALyCORISZImageConfig.FormatEnum;
    base: LoRALyCORISZImageConfig.BaseEnum;
    variant: ZImageVariantType | null;
}
export namespace LoRALyCORISZImageConfig {
    export type TypeEnum = 'lora';
    export const TypeEnum = {
        Lora: 'lora' as TypeEnum
    };
    export type FormatEnum = 'lycoris';
    export const FormatEnum = {
        Lycoris: 'lycoris' as FormatEnum
    };
    export type BaseEnum = 'z-image';
    export const BaseEnum = {
        ZImage: 'z-image' as BaseEnum
    };
}


