/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelSourceType } from './modelSourceType';
import { FluxVariantType } from './fluxVariantType';
import { MainModelDefaultSettings } from './mainModelDefaultSettings';


/**
 * Model config for main checkpoint models.
 */
export interface MainGGUFFLUXConfig { 
    /**
     * A unique key for this model.
     */
    key: string;
    /**
     * The hash of the model file(s).
     */
    hash: string;
    /**
     * Path to the model on the filesystem. Relative paths are relative to the Invoke root directory.
     */
    path: string;
    /**
     * The size of the model in bytes.
     */
    file_size: number;
    /**
     * Name of the model.
     */
    name: string;
    description: string | null;
    /**
     * The original source of the model (path, URL or repo_id).
     */
    source: string;
    /**
     * The type of source
     */
    source_type: ModelSourceType;
    source_api_response: string | null;
    cover_image: string | null;
    type: MainGGUFFLUXConfig.TypeEnum;
    trigger_phrases: Set<string> | null;
    default_settings: MainModelDefaultSettings | null;
    config_path: string | null;
    base: MainGGUFFLUXConfig.BaseEnum;
    format: MainGGUFFLUXConfig.FormatEnum;
    variant: FluxVariantType;
}
export namespace MainGGUFFLUXConfig {
    export type TypeEnum = 'main';
    export const TypeEnum = {
        Main: 'main' as TypeEnum
    };
    export type BaseEnum = 'flux';
    export const BaseEnum = {
        Flux: 'flux' as BaseEnum
    };
    export type FormatEnum = 'gguf_quantized';
    export const FormatEnum = {
        GgufQuantized: 'gguf_quantized' as FormatEnum
    };
}


