/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';
import { ColorField } from './colorField';


/**
 * Generate a mask for a particular color in an ID Map
 */
export interface MaskFromIDInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    color?: ColorField | null;
    /**
     * Threshold for color detection
     */
    threshold?: number;
    /**
     * Whether or not to invert the mask
     */
    invert?: boolean;
    type: MaskFromIDInvocation.TypeEnum;
}
export namespace MaskFromIDInvocation {
    export type TypeEnum = 'mask_from_id';
    export const TypeEnum = {
        MaskFromId: 'mask_from_id' as TypeEnum
    };
}


