/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ControlNetList } from './controlNetList';


export interface MDControlListOutput { 
    control_list: ControlNetList | null;
    type: MDControlListOutput.TypeEnum;
}
export namespace MDControlListOutput {
    export type TypeEnum = 'md_control_list_output';
    export const TypeEnum = {
        MdControlListOutput: 'md_control_list_output' as TypeEnum
    };
}


