/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { T2IAdapterList } from './t2IAdapterList';


export interface MDT2IAdapterListOutput { 
    t2i_adapter_list: T2IAdapterList | null;
    type: MDT2IAdapterListOutput.TypeEnum;
}
export namespace MDT2IAdapterListOutput {
    export type TypeEnum = 'md_ip_adapters_output';
    export const TypeEnum = {
        MdIpAdaptersOutput: 'md_ip_adapters_output' as TypeEnum
    };
}


