/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Detects faces using MediaPipe.
 */
export interface MediaPipeFaceDetectionInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    /**
     * Maximum number of faces to detect
     */
    max_faces?: number;
    /**
     * Minimum confidence for face detection
     */
    min_confidence?: number;
    type: MediaPipeFaceDetectionInvocation.TypeEnum;
}
export namespace MediaPipeFaceDetectionInvocation {
    export type TypeEnum = 'mediapipe_face_detection';
    export const TypeEnum = {
        MediapipeFaceDetection: 'mediapipe_face_detection' as TypeEnum
    };
}


