/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IPAdapterList1 } from './iPAdapterList1';


/**
 * Extracts a IP-Adapters value of a label from metadata
 */
export interface MetadataToIPAdaptersInvocation { 
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    ip_adapter_list?: IPAdapterList1 | null;
    type: MetadataToIPAdaptersInvocation.TypeEnum;
}
export namespace MetadataToIPAdaptersInvocation {
    export type TypeEnum = 'metadata_to_ip_adapters';
    export const TypeEnum = {
        MetadataToIpAdapters: 'metadata_to_ip_adapters' as TypeEnum
    };
}


