/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Extracts an integer value of a label from metadata
 */
export interface MetadataToIntegerInvocation { 
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    /**
     * Label for this metadata item
     */
    label?: MetadataToIntegerInvocation.LabelEnum;
    custom_label?: string | null;
    default_value?: number | null;
    type: MetadataToIntegerInvocation.TypeEnum;
}
export namespace MetadataToIntegerInvocation {
    export type LabelEnum = '* CUSTOM LABEL *' | 'width' | 'height' | 'seed' | 'steps' | 'clip_skip' | 'cfg_scale_start_step' | 'cfg_scale_end_step';
    export const LabelEnum = {
        CustomLabel: '* CUSTOM LABEL *' as LabelEnum,
        Width: 'width' as LabelEnum,
        Height: 'height' as LabelEnum,
        Seed: 'seed' as LabelEnum,
        Steps: 'steps' as LabelEnum,
        ClipSkip: 'clip_skip' as LabelEnum,
        CfgScaleStartStep: 'cfg_scale_start_step' as LabelEnum,
        CfgScaleEndStep: 'cfg_scale_end_step' as LabelEnum
    };
    export type TypeEnum = 'metadata_to_integer';
    export const TypeEnum = {
        MetadataToInteger: 'metadata_to_integer' as TypeEnum
    };
}


