/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Items } from './items';


/**
 * Takes a MetadataItem or collection of MetadataItems and outputs a MetadataDict.
 */
export interface MetadataInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    items?: Items | null;
    type: MetadataInvocation.TypeEnum;
}
export namespace MetadataInvocation {
    export type TypeEnum = 'metadata';
    export const TypeEnum = {
        Metadata: 'metadata' as TypeEnum
    };
}


