/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CLIPField } from './cLIPField';
import { ModelIdentifierField } from './modelIdentifierField';
import { VAEField } from './vAEField';
import { UNetField } from './uNetField';


/**
 * String to main model output
 */
export interface MetadataToModelOutput { 
    /**
     * Main model (UNet, VAE, CLIP) to load
     */
    model: ModelIdentifierField;
    /**
     * Model Name
     */
    name: string;
    /**
     * UNet (scheduler, LoRAs)
     */
    unet: UNetField;
    /**
     * VAE
     */
    vae: VAEField;
    /**
     * CLIP (tokenizer, text encoder, LoRAs) and skipped layer count
     */
    clip: CLIPField;
    type: MetadataToModelOutput.TypeEnum;
}
export namespace MetadataToModelOutput {
    export type TypeEnum = 'metadata_to_model_output';
    export const TypeEnum = {
        MetadataToModelOutput: 'metadata_to_model_output' as TypeEnum
    };
}


