/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Extracts a string value of a label from metadata
 */
export interface MetadataToStringInvocation { 
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    /**
     * Label for this metadata item
     */
    label?: MetadataToStringInvocation.LabelEnum;
    custom_label?: string | null;
    default_value?: string | null;
    type: MetadataToStringInvocation.TypeEnum;
}
export namespace MetadataToStringInvocation {
    export type LabelEnum = '* CUSTOM LABEL *' | 'positive_prompt' | 'positive_style_prompt' | 'negative_prompt' | 'negative_style_prompt';
    export const LabelEnum = {
        CustomLabel: '* CUSTOM LABEL *' as LabelEnum,
        PositivePrompt: 'positive_prompt' as LabelEnum,
        PositiveStylePrompt: 'positive_style_prompt' as LabelEnum,
        NegativePrompt: 'negative_prompt' as LabelEnum,
        NegativeStylePrompt: 'negative_style_prompt' as LabelEnum
    };
    export type TypeEnum = 'metadata_to_string';
    export const TypeEnum = {
        MetadataToString: 'metadata_to_string' as TypeEnum
    };
}


