/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Extracts a Boolean value Collection of a label from metadata
 */
export interface MetadataToBoolCollectionInvocation { 
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    /**
     * Label for this metadata item
     */
    label?: MetadataToBoolCollectionInvocation.LabelEnum;
    custom_label?: string | null;
    default_value?: Array<boolean> | null;
    type: MetadataToBoolCollectionInvocation.TypeEnum;
}
export namespace MetadataToBoolCollectionInvocation {
    export type LabelEnum = '* CUSTOM LABEL *' | 'seamless_x' | 'seamless_y';
    export const LabelEnum = {
        CustomLabel: '* CUSTOM LABEL *' as LabelEnum,
        SeamlessX: 'seamless_x' as LabelEnum,
        SeamlessY: 'seamless_y' as LabelEnum
    };
    export type TypeEnum = 'metadata_to_bool_collection';
    export const TypeEnum = {
        MetadataToBoolCollection: 'metadata_to_bool_collection' as TypeEnum
    };
}


