/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Source } from './source';


/**
 * Event model for model_install_cancelled
 */
export interface ModelInstallCancelledEvent { 
    /**
     * The timestamp of the event
     */
    timestamp: number;
    /**
     * The ID of the install job
     */
    id: number;
    source: Source;
}

