/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model source type.
 */
export type ModelSourceType = 'path' | 'url' | 'hf_repo_id';

export const ModelSourceType = {
    Path: 'path' as ModelSourceType,
    Url: 'url' as ModelSourceType,
    HfRepoId: 'hf_repo_id' as ModelSourceType
};

