/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RemoteModelFile } from './remoteModelFile';
import { BaseMetadata } from './baseMetadata';
import { HuggingFaceMetadata } from './huggingFaceMetadata';


/**
 * @type ModelInstallJobSourceMetadata
 * @export
 */
export type ModelInstallJobSourceMetadata = BaseMetadata | HuggingFaceMetadata;

