/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PartsInnerValue1 } from './partsInnerValue1';
import { Source } from './source';


/**
 * Event model for model_install_download_started
 */
export interface ModelInstallDownloadStartedEvent { 
    /**
     * The timestamp of the event
     */
    timestamp: number;
    /**
     * The ID of the install job
     */
    id: number;
    source: Source;
    /**
     * Where model is downloading to
     */
    local_path: string;
    /**
     * Number of bytes downloaded so far
     */
    bytes: number;
    /**
     * Total size of download, including all files
     */
    total_bytes: number;
    /**
     * Progress of downloading URLs that comprise the model, if any
     */
    parts: Array<{ [key: string]: PartsInnerValue1; }>;
}

