/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelRelationshipCreateRequest { 
    /**
     * The key of the first model in the relationship
     */
    model_key_1: string;
    /**
     * The key of the second model in the relationship
     */
    model_key_2: string;
}

