/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Various hugging face variants on the diffusers format.
 */
export type ModelRepoVariant = '' | 'fp16' | 'fp32' | 'onnx' | 'openvino' | 'flax';

export const ModelRepoVariant = {
    Empty: '' as ModelRepoVariant,
    Fp16: 'fp16' as ModelRepoVariant,
    Fp32: 'fp32' as ModelRepoVariant,
    Onnx: 'onnx' as ModelRepoVariant,
    Openvino: 'openvino' as ModelRepoVariant,
    Flax: 'flax' as ModelRepoVariant
};

