/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FluxConditioningField } from './fluxConditioningField';
import { TensorField } from './tensorField';


/**
 * Negative conditioning tensor. Can be None if cfg_scale is 1.0.
 */
export interface NegativeTextConditioning { 
    /**
     * The name of conditioning tensor
     */
    conditioning_name: string;
    mask?: TensorField;
}

