/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Value } from './value';


export interface NodeFieldValue { 
    /**
     * The node into which this batch data item will be substituted.
     */
    node_path: string;
    /**
     * The field into which this batch data item will be substituted.
     */
    field_name: string;
    value: Value;
}

