/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LatentsField } from './latentsField';


/**
 * Invocation noise output
 */
export interface NoiseOutput { 
    /**
     * Noise tensor
     */
    noise: LatentsField;
    /**
     * Width of output (px)
     */
    width: number;
    /**
     * Height of output (px)
     */
    height: number;
    type: NoiseOutput.TypeEnum;
}
export namespace NoiseOutput {
    export type TypeEnum = 'noise_output';
    export const TypeEnum = {
        NoiseOutput: 'noise_output' as TypeEnum
    };
}


