/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoardDTO } from './boardDTO';


export interface OffsetPaginatedResultsBoardDTO { 
    /**
     * Limit of items to get
     */
    limit: number;
    /**
     * Offset from which to retrieve items
     */
    offset: number;
    /**
     * Total number of items in result
     */
    total: number;
    /**
     * Items
     */
    items: Array<BoardDTO>;
}

