/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowRecordListItemWithThumbnailDTO } from './workflowRecordListItemWithThumbnailDTO';


export interface PaginatedResultsWorkflowRecordListItemWithThumbnailDTO { 
    /**
     * Current Page
     */
    page: number;
    /**
     * Total number of pages
     */
    pages: number;
    /**
     * Number of items per page
     */
    per_page: number;
    /**
     * Total number of items in result
     */
    total: number;
    /**
     * Items
     */
    items: Array<WorkflowRecordListItemWithThumbnailDTO>;
}

