/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { BoardField } from './boardField';


/**
 * Generate Normal, Displacement and Roughness Map from a given image
 */
export interface PBRMapsInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    /**
     * Tile size
     */
    tile_size?: number;
    /**
     * Border mode to apply to eliminate any artifacts or seams
     */
    border_mode?: PBRMapsInvocation.BorderModeEnum;
    type: PBRMapsInvocation.TypeEnum;
}
export namespace PBRMapsInvocation {
    export type BorderModeEnum = 'none' | 'seamless' | 'mirror' | 'replicate';
    export const BorderModeEnum = {
        None: 'none' as BorderModeEnum,
        Seamless: 'seamless' as BorderModeEnum,
        Mirror: 'mirror' as BorderModeEnum,
        Replicate: 'replicate' as BorderModeEnum
    };
    export type TypeEnum = 'pbr_maps';
    export const TypeEnum = {
        PbrMaps: 'pbr_maps' as TypeEnum
    };
}


