/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';


export interface PBRMapsOutput { 
    /**
     * The generated normal map
     */
    normal_map: ImageField;
    /**
     * The generated roughness map
     */
    roughness_map: ImageField;
    /**
     * The generated displacement map
     */
    displacement_map: ImageField;
    type: PBRMapsOutput.TypeEnum;
}
export namespace PBRMapsOutput {
    export type TypeEnum = 'pbr_maps-output';
    export const TypeEnum = {
        PbrMapsOutput: 'pbr_maps-output' as TypeEnum
    };
}


