/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StylePresetField } from './stylePresetField';


/**
 * Applies a Style Preset template to positive and negative prompts.  Select a Style Preset and provide positive/negative prompts. The node replaces {prompt} placeholders in the template with your input prompts.
 */
export interface PromptTemplateInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    style_preset?: StylePresetField | null;
    /**
     * The positive prompt to insert into the template\'s {prompt} placeholder
     */
    positive_prompt?: string;
    /**
     * The negative prompt to insert into the template\'s {prompt} placeholder
     */
    negative_prompt?: string;
    type: PromptTemplateInvocation.TypeEnum;
}
export namespace PromptTemplateInvocation {
    export type TypeEnum = 'prompt_template';
    export const TypeEnum = {
        PromptTemplate: 'prompt_template' as TypeEnum
    };
}


