/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Loads prompts from a text file
 */
export interface PromptsFromFileInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    file_path?: string | null;
    pre_prompt?: string | null;
    post_prompt?: string | null;
    /**
     * Line in the file to start start from
     */
    start_line?: number;
    /**
     * Max lines to read from file (0=all)
     */
    max_prompts?: number;
    type: PromptsFromFileInvocation.TypeEnum;
}
export namespace PromptsFromFileInvocation {
    export type TypeEnum = 'prompt_from_file';
    export const TypeEnum = {
        PromptFromFile: 'prompt_from_file' as TypeEnum
    };
}


