/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Output for the Prompt Template node
 */
export interface PromptTemplateOutput { 
    /**
     * The positive prompt with the template applied
     */
    positive_prompt: string;
    /**
     * The negative prompt with the template applied
     */
    negative_prompt: string;
    type: PromptTemplateOutput.TypeEnum;
}
export namespace PromptTemplateOutput {
    export type TypeEnum = 'prompt_template_output';
    export const TypeEnum = {
        PromptTemplateOutput: 'prompt_template_output' as TypeEnum
    };
}


