/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Event model for queue_cleared
 */
export interface QueueClearedEvent { 
    /**
     * The timestamp of the event
     */
    timestamp: number;
    /**
     * The ID of the queue
     */
    queue_id: string;
}

