/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RemoveImagesFromBoardResult { 
    /**
     * The ids of boards affected by the delete operation
     */
    affected_boards: Array<string>;
    /**
     * The image names that were removed from their board
     */
    removed_images: Array<string>;
}

