/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about a downloadable file that forms part of a model.
 */
export interface RemoteModelFile { 
    /**
     * The url to download this model file
     */
    url: string;
    /**
     * The path to the file, relative to the model root
     */
    path: string;
    size?: number | null;
    sha256?: string | null;
}

