/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The origin of a resource (eg image).  - INTERNAL: The resource was created by the application. - EXTERNAL: The resource was not created by the application. This may be a user-initiated upload, or an internal application upload (eg Canvas init image).
 */
export type ResourceOrigin = 'internal' | 'external';

export const ResourceOrigin = {
    Internal: 'internal' as ResourceOrigin,
    External: 'external' as ResourceOrigin
};

