/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdatedAt2 } from './updatedAt2';
import { CreatedAt2 } from './createdAt2';
import { SessionQueueItem } from './sessionQueueItem';
import { WorkflowWithoutID } from './workflowWithoutID';
import { GraphExecutionState } from './graphExecutionState';
import { NodeFieldValue } from './nodeFieldValue';
import { CompletedAt } from './completedAt';
import { StartedAt } from './startedAt';


export interface Response200GetNextQueueItem { 
    /**
     * The identifier of the session queue item
     */
    item_id: number;
    /**
     * The status of this queue item
     */
    status: Response200GetNextQueueItem.StatusEnum;
    /**
     * The priority of this queue item
     */
    priority: number;
    /**
     * The ID of the batch associated with this queue item
     */
    batch_id: string;
    origin?: string;
    destination?: string;
    /**
     * The ID of the session associated with this queue item. The session doesn\'t exist in graph_executions until the queue item is executed.
     */
    session_id: string;
    error_type?: string;
    error_message?: string;
    error_traceback?: string;
    created_at: CreatedAt2;
    updated_at: UpdatedAt2;
    started_at?: StartedAt | null;
    completed_at?: CompletedAt | null;
    /**
     * The id of the queue with which this item is associated
     */
    queue_id: string;
    /**
     * The id of the user who created this queue item
     */
    user_id?: string;
    user_display_name?: string;
    user_email?: string;
    field_values?: Array<NodeFieldValue>;
    retried_from_item_id?: number;
    /**
     * The fully-populated session to be executed
     */
    session: GraphExecutionState;
    workflow?: WorkflowWithoutID;
}
export namespace Response200GetNextQueueItem {
    export type StatusEnum = 'pending' | 'in_progress' | 'completed' | 'failed' | 'canceled';
    export const StatusEnum = {
        Pending: 'pending' as StatusEnum,
        InProgress: 'in_progress' as StatusEnum,
        Completed: 'completed' as StatusEnum,
        Failed: 'failed' as StatusEnum,
        Canceled: 'canceled' as StatusEnum
    };
}


