/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Scheduler prediction type.
 */
export type SchedulerPredictionType = 'epsilon' | 'v_prediction' | 'sample';

export const SchedulerPredictionType = {
    Epsilon: 'epsilon' as SchedulerPredictionType,
    VPrediction: 'v_prediction' as SchedulerPredictionType,
    Sample: 'sample' as SchedulerPredictionType
};

