/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SD3ConditioningField } from './sD3ConditioningField';


/**
 * Base class for nodes that output a single SD3 conditioning tensor
 */
export interface SD3ConditioningOutput { 
    /**
     * Conditioning tensor
     */
    conditioning: SD3ConditioningField;
    type: SD3ConditioningOutput.TypeEnum;
}
export namespace SD3ConditioningOutput {
    export type TypeEnum = 'sd3_conditioning_output';
    export const TypeEnum = {
        Sd3ConditioningOutput: 'sd3_conditioning_output' as TypeEnum
    };
}


