/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CLIPField } from './cLIPField';
import { ModelIdentifierField } from './modelIdentifierField';
import { UNetField } from './uNetField';


/**
 * Apply selected lora to unet and text_encoder.
 */
export interface SDXLLoRALoaderInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    lora?: ModelIdentifierField | null;
    /**
     * The weight at which the LoRA is applied to each model
     */
    weight?: number;
    unet?: UNetField | null;
    clip?: CLIPField | null;
    clip2?: CLIPField | null;
    type: SDXLLoRALoaderInvocation.TypeEnum;
}
export namespace SDXLLoRALoaderInvocation {
    export type TypeEnum = 'sdxl_lora_loader';
    export const TypeEnum = {
        SdxlLoraLoader: 'sdxl_lora_loader' as TypeEnum
    };
}


