/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VAEField } from './vAEField';
import { UNetField } from './uNetField';


/**
 * Modified Seamless Model output
 */
export interface SeamlessModeOutput { 
    unet: UNetField | null;
    vae: VAEField | null;
    type: SeamlessModeOutput.TypeEnum;
}
export namespace SeamlessModeOutput {
    export type TypeEnum = 'seamless_output';
    export const TypeEnum = {
        SeamlessOutput: 'seamless_output' as TypeEnum
    };
}


