/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SessionQueueCountsByDestination { 
    /**
     * The ID of the queue
     */
    queue_id: string;
    /**
     * The destination of queue items included in this status
     */
    destination: string;
    /**
     * Number of queue items with status \'pending\' for the destination
     */
    pending: number;
    /**
     * Number of queue items with status \'in_progress\' for the destination
     */
    in_progress: number;
    /**
     * Number of queue items with status \'complete\' for the destination
     */
    completed: number;
    /**
     * Number of queue items with status \'error\' for the destination
     */
    failed: number;
    /**
     * Number of queue items with status \'canceled\' for the destination
     */
    canceled: number;
    /**
     * Total number of queue items for the destination
     */
    total: number;
}

