/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Path } from './path';
import { HFModelSource } from './hFModelSource';
import { ModelRepoVariant } from './modelRepoVariant';
import { URLModelSource } from './uRLModelSource';
import { LocalModelSource } from './localModelSource';


/**
 * Source (URL, repo_id, or local path) of model
 */
/**
 * @type Source1
 * Source (URL, repo_id, or local path) of model
 * @export
 */
export type Source1 = HFModelSource | LocalModelSource | URLModelSource;

