/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageField } from './imageField';
import { ModelIdentifierField } from './modelIdentifierField';
import { BoardField } from './boardField';


/**
 * Run any spandrel image-to-image model (https://github.com/chaiNNer-org/spandrel) until the target scale is reached.
 */
export interface SpandrelImageToImageAutoscaleInvocation { 
    board?: BoardField | null;
    /**
     * Pydantic model for metadata with custom root of type dict[str, Any]. Metadata is stored without a strict schema.
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    image?: ImageField | null;
    image_to_image_model?: ModelIdentifierField | null;
    /**
     * The tile size for tiled image-to-image. Set to 0 to disable tiling.
     */
    tile_size?: number;
    type: SpandrelImageToImageAutoscaleInvocation.TypeEnum;
    /**
     * The final scale of the output image. If the model does not upscale the image, this will be ignored.
     */
    scale?: number;
    /**
     * If true, the output image will be resized to the nearest multiple of 8 in both dimensions.
     */
    fit_to_multiple_of_8?: boolean;
}
export namespace SpandrelImageToImageAutoscaleInvocation {
    export type TypeEnum = 'spandrel_image_to_image_autoscale';
    export const TypeEnum = {
        SpandrelImageToImageAutoscale: 'spandrel_image_to_image_autoscale' as TypeEnum
    };
}


