/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelSourceType } from './modelSourceType';


/**
 * Model config for Spandrel Image to Image models.
 */
export interface SpandrelCheckpointConfig { 
    /**
     * A unique key for this model.
     */
    key: string;
    /**
     * The hash of the model file(s).
     */
    hash: string;
    /**
     * Path to the model on the filesystem. Relative paths are relative to the Invoke root directory.
     */
    path: string;
    /**
     * The size of the model in bytes.
     */
    file_size: number;
    /**
     * Name of the model.
     */
    name: string;
    description: string | null;
    /**
     * The original source of the model (path, URL or repo_id).
     */
    source: string;
    /**
     * The type of source
     */
    source_type: ModelSourceType;
    source_api_response: string | null;
    cover_image: string | null;
    base: SpandrelCheckpointConfig.BaseEnum;
    type: SpandrelCheckpointConfig.TypeEnum;
    format: SpandrelCheckpointConfig.FormatEnum;
}
export namespace SpandrelCheckpointConfig {
    export type BaseEnum = 'any';
    export const BaseEnum = {
        Any: 'any' as BaseEnum
    };
    export type TypeEnum = 'spandrel_image_to_image';
    export const TypeEnum = {
        SpandrelImageToImage: 'spandrel_image_to_image' as TypeEnum
    };
    export type FormatEnum = 'checkpoint';
    export const FormatEnum = {
        Checkpoint: 'checkpoint' as FormatEnum
    };
}


