/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Base class for nodes that output a collection of strings
 */
export interface StringGeneratorOutput { 
    /**
     * The generated strings
     */
    strings: Array<string>;
    type: StringGeneratorOutput.TypeEnum;
}
export namespace StringGeneratorOutput {
    export type TypeEnum = 'string_generator_output';
    export const TypeEnum = {
        StringGeneratorOutput: 'string_generator_output' as TypeEnum
    };
}


