/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PresetData } from './presetData';
import { PresetType } from './presetType';


export interface StylePresetRecordWithImage { 
    /**
     * The name of the style preset.
     */
    name: string;
    /**
     * The preset data
     */
    preset_data: PresetData;
    /**
     * The type of style preset
     */
    type: PresetType;
    /**
     * The style preset ID.
     */
    id: string;
    image: string | null;
}
export namespace StylePresetRecordWithImage {
}


