/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Submodel type.
 */
export type SubModelType = 'unet' | 'transformer' | 'text_encoder' | 'text_encoder_2' | 'text_encoder_3' | 'tokenizer' | 'tokenizer_2' | 'tokenizer_3' | 'vae' | 'vae_decoder' | 'vae_encoder' | 'scheduler' | 'safety_checker';

export const SubModelType = {
    Unet: 'unet' as SubModelType,
    Transformer: 'transformer' as SubModelType,
    TextEncoder: 'text_encoder' as SubModelType,
    TextEncoder2: 'text_encoder_2' as SubModelType,
    TextEncoder3: 'text_encoder_3' as SubModelType,
    Tokenizer: 'tokenizer' as SubModelType,
    Tokenizer2: 'tokenizer_2' as SubModelType,
    Tokenizer3: 'tokenizer_3' as SubModelType,
    Vae: 'vae' as SubModelType,
    VaeDecoder: 'vae_decoder' as SubModelType,
    VaeEncoder: 'vae_encoder' as SubModelType,
    Scheduler: 'scheduler' as SubModelType,
    SafetyChecker: 'safety_checker' as SubModelType
};

