/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { T2IAdapterField } from './t2IAdapterField';


export interface T2IAdapterOutput { 
    /**
     * T2I-Adapter(s) to apply
     */
    t2i_adapter: T2IAdapterField;
    type: T2IAdapterOutput.TypeEnum;
}
export namespace T2IAdapterOutput {
    export type TypeEnum = 't2i_adapter_output';
    export const TypeEnum = {
        T2iAdapterOutput: 't2i_adapter_output' as TypeEnum
    };
}


