/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConditioningField } from './conditioningField';
import { CFGScale3 } from './cFGScale3';
import { UNetField } from './uNetField';
import { Control2 } from './control2';
import { LatentsField } from './latentsField';


/**
 * Tiled Multi-Diffusion denoising.  This node handles automatically tiling the input image, and is primarily intended for global refinement of images in tiled upscaling workflows. Future Multi-Diffusion nodes should allow the user to specify custom regions with different parameters for each region to harness the full power of Multi-Diffusion.  This node has a similar interface to the `DenoiseLatents` node, but it has a reduced feature set (no IP-Adapter, T2I-Adapter, masking, etc.).
 */
export interface TiledMultiDiffusionDenoiseLatents { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    positive_conditioning?: ConditioningField | null;
    negative_conditioning?: ConditioningField | null;
    noise?: LatentsField | null;
    latents?: LatentsField | null;
    /**
     * Height of the tiles in image space.
     */
    tile_height?: number;
    /**
     * Width of the tiles in image space.
     */
    tile_width?: number;
    /**
     * The overlap between adjacent tiles in pixel space. (Of course, tile merging is applied in latent space.) Tiles will be cropped during merging (if necessary) to ensure that they overlap by exactly this amount.
     */
    tile_overlap?: number;
    /**
     * Number of steps to run
     */
    steps?: number;
    cfg_scale?: CFGScale3;
    /**
     * When to start denoising, expressed a percentage of total steps
     */
    denoising_start?: number;
    /**
     * When to stop denoising, expressed a percentage of total steps
     */
    denoising_end?: number;
    /**
     * Scheduler to use during inference
     */
    scheduler?: TiledMultiDiffusionDenoiseLatents.SchedulerEnum;
    unet?: UNetField | null;
    /**
     * Rescale multiplier for CFG guidance, used for models trained with zero-terminal SNR
     */
    cfg_rescale_multiplier?: number;
    control?: Control2 | null;
    type: TiledMultiDiffusionDenoiseLatents.TypeEnum;
}
export namespace TiledMultiDiffusionDenoiseLatents {
    export type SchedulerEnum = 'ddim' | 'ddpm' | 'deis' | 'deis_k' | 'lms' | 'lms_k' | 'pndm' | 'heun' | 'heun_k' | 'euler' | 'euler_k' | 'euler_a' | 'kdpm_2' | 'kdpm_2_k' | 'kdpm_2_a' | 'kdpm_2_a_k' | 'dpmpp_2s' | 'dpmpp_2s_k' | 'dpmpp_2m' | 'dpmpp_2m_k' | 'dpmpp_2m_sde' | 'dpmpp_2m_sde_k' | 'dpmpp_3m' | 'dpmpp_3m_k' | 'dpmpp_sde' | 'dpmpp_sde_k' | 'unipc' | 'unipc_k' | 'lcm' | 'tcd';
    export const SchedulerEnum = {
        Ddim: 'ddim' as SchedulerEnum,
        Ddpm: 'ddpm' as SchedulerEnum,
        Deis: 'deis' as SchedulerEnum,
        DeisK: 'deis_k' as SchedulerEnum,
        Lms: 'lms' as SchedulerEnum,
        LmsK: 'lms_k' as SchedulerEnum,
        Pndm: 'pndm' as SchedulerEnum,
        Heun: 'heun' as SchedulerEnum,
        HeunK: 'heun_k' as SchedulerEnum,
        Euler: 'euler' as SchedulerEnum,
        EulerK: 'euler_k' as SchedulerEnum,
        EulerA: 'euler_a' as SchedulerEnum,
        Kdpm2: 'kdpm_2' as SchedulerEnum,
        Kdpm2K: 'kdpm_2_k' as SchedulerEnum,
        Kdpm2A: 'kdpm_2_a' as SchedulerEnum,
        Kdpm2AK: 'kdpm_2_a_k' as SchedulerEnum,
        Dpmpp2s: 'dpmpp_2s' as SchedulerEnum,
        Dpmpp2sK: 'dpmpp_2s_k' as SchedulerEnum,
        Dpmpp2m: 'dpmpp_2m' as SchedulerEnum,
        Dpmpp2mK: 'dpmpp_2m_k' as SchedulerEnum,
        Dpmpp2mSde: 'dpmpp_2m_sde' as SchedulerEnum,
        Dpmpp2mSdeK: 'dpmpp_2m_sde_k' as SchedulerEnum,
        Dpmpp3m: 'dpmpp_3m' as SchedulerEnum,
        Dpmpp3mK: 'dpmpp_3m_k' as SchedulerEnum,
        DpmppSde: 'dpmpp_sde' as SchedulerEnum,
        DpmppSdeK: 'dpmpp_sde_k' as SchedulerEnum,
        Unipc: 'unipc' as SchedulerEnum,
        UnipcK: 'unipc_k' as SchedulerEnum,
        Lcm: 'lcm' as SchedulerEnum,
        Tcd: 'tcd' as SchedulerEnum
    };
    export type TypeEnum = 'tiled_multi_diffusion_denoise_latents';
    export const TypeEnum = {
        TiledMultiDiffusionDenoiseLatents: 'tiled_multi_diffusion_denoise_latents' as TypeEnum
    };
}


