/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Classification } from './classification';


/**
 * Provides additional node configuration to the UI. This is used internally by the @invocation decorator logic. Do not use this directly.
 */
export interface UIConfigBase { 
    tags: Array<string> | null;
    title: string | null;
    category: string | null;
    /**
     * The node\'s version. Should be a valid semver string e.g. \"1.0.0\" or \"3.8.13\".
     */
    version: string;
    /**
     * The node pack that this node belongs to, will be \'invokeai\' for built-in nodes
     */
    node_pack: string;
    /**
     * The node\'s classification
     */
    classification: Classification;
}
export namespace UIConfigBase {
}


