/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UNetField } from './uNetField';


/**
 * Base class for invocations that output a UNet field.
 */
export interface UNetOutput { 
    /**
     * UNet (scheduler, LoRAs)
     */
    unet: UNetField;
    type: UNetOutput.TypeEnum;
}
export namespace UNetOutput {
    export type TypeEnum = 'unet_output';
    export const TypeEnum = {
        UnetOutput: 'unet_output' as TypeEnum
    };
}


