/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A generic URL point to a checkpoint file.
 */
export interface URLModelSource { 
    url: string;
    access_token?: string | null;
    type?: URLModelSource.TypeEnum;
}
export namespace URLModelSource {
    export type TypeEnum = 'url';
    export const TypeEnum = {
        Url: 'url' as TypeEnum
    };
}


