/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelSourceType } from './modelSourceType';
import { ModelRepoVariant } from './modelRepoVariant';


/**
 * Model config for FLUX.2 VAE models in diffusers format (AutoencoderKLFlux2).
 */
export interface VAEDiffusersFlux2Config { 
    /**
     * A unique key for this model.
     */
    key: string;
    /**
     * The hash of the model file(s).
     */
    hash: string;
    /**
     * Path to the model on the filesystem. Relative paths are relative to the Invoke root directory.
     */
    path: string;
    /**
     * The size of the model in bytes.
     */
    file_size: number;
    /**
     * Name of the model.
     */
    name: string;
    description: string | null;
    /**
     * The original source of the model (path, URL or repo_id).
     */
    source: string;
    /**
     * The type of source
     */
    source_type: ModelSourceType;
    source_api_response: string | null;
    cover_image: string | null;
    format: VAEDiffusersFlux2Config.FormatEnum;
    repo_variant: ModelRepoVariant;
    type: VAEDiffusersFlux2Config.TypeEnum;
    base: VAEDiffusersFlux2Config.BaseEnum;
}
export namespace VAEDiffusersFlux2Config {
    export type FormatEnum = 'diffusers';
    export const FormatEnum = {
        Diffusers: 'diffusers' as FormatEnum
    };
    export type TypeEnum = 'vae';
    export const TypeEnum = {
        Vae: 'vae' as TypeEnum
    };
    export type BaseEnum = 'flux2';
    export const BaseEnum = {
        Flux2: 'flux2' as BaseEnum
    };
}


