/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VAEField } from './vAEField';


/**
 * Base class for invocations that output a VAE field
 */
export interface VAEOutput { 
    /**
     * VAE
     */
    vae: VAEField;
    type: VAEOutput.TypeEnum;
}
export namespace VAEOutput {
    export type TypeEnum = 'vae_output';
    export const TypeEnum = {
        VaeOutput: 'vae_output' as TypeEnum
    };
}


