/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OpenedAt } from './openedAt';
import { UpdatedAt3 } from './updatedAt3';
import { WorkflowCategory } from './workflowCategory';
import { CreatedAt3 } from './createdAt3';


export interface WorkflowRecordListItemWithThumbnailDTO { 
    /**
     * The id of the workflow.
     */
    workflow_id: string;
    /**
     * The name of the workflow.
     */
    name: string;
    created_at: CreatedAt3;
    updated_at: UpdatedAt3;
    opened_at?: OpenedAt | null;
    /**
     * The description of the workflow.
     */
    description: string;
    /**
     * The description of the workflow.
     */
    category: WorkflowCategory;
    /**
     * The tags of the workflow.
     */
    tags: string;
    thumbnail_url?: string | null;
}
export namespace WorkflowRecordListItemWithThumbnailDTO {
}


