/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The order by options for workflow records
 */
export type WorkflowRecordOrderBy = 'created_at' | 'updated_at' | 'opened_at' | 'name';

export const WorkflowRecordOrderBy = {
    CreatedAt: 'created_at' as WorkflowRecordOrderBy,
    UpdatedAt: 'updated_at' as WorkflowRecordOrderBy,
    OpenedAt: 'opened_at' as WorkflowRecordOrderBy,
    Name: 'name' as WorkflowRecordOrderBy
};

