/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelIdentifierField } from './modelIdentifierField';


/**
 * A Z-Image control conditioning field for spatial control (Canny, HED, Depth, Pose, MLSD).
 */
export interface ZImageControlField { 
    /**
     * The name of the preprocessed control image
     */
    image_name: string;
    /**
     * The Z-Image ControlNet adapter model
     */
    control_model: ModelIdentifierField;
    /**
     * The strength of the control signal. Recommended range: 0.65-0.80.
     */
    control_context_scale?: number;
    /**
     * When the control is first applied (% of total steps)
     */
    begin_step_percent?: number;
    /**
     * When the control is last applied (% of total steps)
     */
    end_step_percent?: number;
}

