/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZImageConditioningField } from './zImageConditioningField';


/**
 * Base class for nodes that output a Z-Image text conditioning tensor.
 */
export interface ZImageConditioningOutput { 
    /**
     * Conditioning tensor
     */
    conditioning: ZImageConditioningField;
    type: ZImageConditioningOutput.TypeEnum;
}
export namespace ZImageConditioningOutput {
    export type TypeEnum = 'z_image_conditioning_output';
    export const TypeEnum = {
        ZImageConditioningOutput: 'z_image_conditioning_output' as TypeEnum
    };
}


