/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TensorField } from './tensorField';
import { Qwen3EncoderField } from './qwen3EncoderField';


/**
 * Encodes and preps a prompt for a Z-Image image.  Supports regional prompting by connecting a mask input.
 */
export interface ZImageTextEncoderInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    prompt?: string | null;
    qwen3_encoder?: Qwen3EncoderField | null;
    mask?: TensorField | null;
    type: ZImageTextEncoderInvocation.TypeEnum;
}
export namespace ZImageTextEncoderInvocation {
    export type TypeEnum = 'z_image_text_encoder';
    export const TypeEnum = {
        ZImageTextEncoder: 'z_image_text_encoder' as TypeEnum
    };
}


