/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TensorField } from './tensorField';


/**
 * A Z-Image conditioning tensor primitive value
 */
export interface ZImageConditioningField { 
    /**
     * The name of conditioning tensor
     */
    conditioning_name: string;
    mask?: TensorField | null;
}

