/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransformerField } from './transformerField';
import { Qwen3EncoderField } from './qwen3EncoderField';


/**
 * Z-Image LoRA Loader Output
 */
export interface ZImageLoRALoaderOutput { 
    transformer: TransformerField | null;
    qwen3_encoder: Qwen3EncoderField | null;
    type: ZImageLoRALoaderOutput.TypeEnum;
}
export namespace ZImageLoRALoaderOutput {
    export type TypeEnum = 'z_image_lora_loader_output';
    export const TypeEnum = {
        ZImageLoraLoaderOutput: 'z_image_lora_loader_output' as TypeEnum
    };
}


