/**
 * Invoke - Community Edition
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelIdentifierField } from './modelIdentifierField';
import { TransformerField } from './transformerField';
import { Qwen3EncoderField } from './qwen3EncoderField';


/**
 * Apply a LoRA model to a Z-Image transformer and/or Qwen3 text encoder.
 */
export interface ZImageLoRALoaderInvocation { 
    /**
     * The id of this instance of an invocation. Must be unique among all instances of invocations.
     */
    id: string;
    /**
     * Whether or not this is an intermediate invocation.
     */
    is_intermediate?: boolean;
    /**
     * Whether or not to use the cache
     */
    use_cache?: boolean;
    lora?: ModelIdentifierField | null;
    /**
     * The weight at which the LoRA is applied to each model
     */
    weight?: number;
    transformer?: TransformerField | null;
    qwen3_encoder?: Qwen3EncoderField | null;
    type: ZImageLoRALoaderInvocation.TypeEnum;
}
export namespace ZImageLoRALoaderInvocation {
    export type TypeEnum = 'z_image_lora_loader';
    export const TypeEnum = {
        ZImageLoraLoader: 'z_image_lora_loader' as TypeEnum
    };
}


