/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { URLCitationDto } from './uRLCitationDto';


export interface AnnotationDto { 
    /**
     * The type of the URL citation. Always `url_citation`.
     */
    type: AnnotationDto.TypeEnum;
    /**
     * A URL citation when using web search.
     */
    url_citation: URLCitationDto;
}
export namespace AnnotationDto {
    export const TypeEnum = {
        UrlCitation: 'url_citation'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


