/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatResponseDto } from './chatResponseDto';
import { ChatRequestDto } from './chatRequestDto';


export interface ChatEntryDto { 
    /**
     * ObjectId of the owning user
     */
    userId: string;
    internalChatId: string;
    /**
     * ChatMetadata ObjectId reference
     */
    chatInternalId?: object | null;
    name?: object | null;
    request: ChatRequestDto;
    response: ChatResponseDto;
    /**
     * LM Studio response ID of the previous turn
     */
    previousResponseId?: object | null;
    /**
     * LM Studio response ID returned for this turn
     */
    responseId?: object | null;
    createdAt: string;
    updatedAt: string;
}

