/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AudioDto } from './audioDto';
import { ChatCompletionAssistantMessageParamDtoToolCallsInner } from './chatCompletionAssistantMessageParamDtoToolCallsInner';
import { FunctionCallDto } from './functionCallDto';
import { ChatCompletionAssistantMessageParamDtoContentInner } from './chatCompletionAssistantMessageParamDtoContentInner';


export interface ChatCompletionAssistantMessageParamDto { 
    /**
     * The role of the messages author, in this case `assistant`.
     */
    role: ChatCompletionAssistantMessageParamDto.RoleEnum;
    /**
     * Data about a previous audio response from the model.   [Learn more](https://platform.openai.com/docs/guides/audio).
     */
    audio?: AudioDto;
    /**
     * The contents of the assistant message. Required unless `tool_calls` or   `function_call` is specified.
     */
    content?: Array<ChatCompletionAssistantMessageParamDtoContentInner>;
    function_call?: FunctionCallDto;
    /**
     * An optional name for the participant. Provides the model information to   differentiate between participants of the same role.
     */
    name?: string;
    /**
     * The refusal message by the assistant.
     */
    refusal?: string;
    /**
     * The tool calls generated by the model, such as function calls.
     */
    tool_calls?: Array<ChatCompletionAssistantMessageParamDtoToolCallsInner>;
}
export namespace ChatCompletionAssistantMessageParamDto {
    export const RoleEnum = {
        Assistant: 'assistant'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


