/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvalidToolCallOutputDto } from './invalidToolCallOutputDto';
import { InvalidToolCallMetadataDto } from './invalidToolCallMetadataDto';
import { ProviderInfoDto } from './providerInfoDto';
import { ToolCallOutputDto } from './toolCallOutputDto';
import { ReasoningOutputDto } from './reasoningOutputDto';
import { MessageOutputDto } from './messageOutputDto';


/**
 * @type ChatResponseDtoOutputInner
 * @export
 */
export type ChatResponseDtoOutputInner = InvalidToolCallOutputDto | MessageOutputDto | ReasoningOutputDto | ToolCallOutputDto;

