/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatCompletionUserMessageParamDtoContentInner } from './chatCompletionUserMessageParamDtoContentInner';


export interface ChatCompletionUserMessageParamDto { 
    /**
     * The contents of the user message.
     */
    content: Array<ChatCompletionUserMessageParamDtoContentInner>;
    /**
     * The role of the messages author, in this case `user`.
     */
    role: ChatCompletionUserMessageParamDto.RoleEnum;
    /**
     * An optional name for the participant. Provides the model information to   differentiate between participants of the same role.
     */
    name?: string;
}
export namespace ChatCompletionUserMessageParamDto {
    export const RoleEnum = {
        User: 'user'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


