/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatRequestDtoIntegrationsInner } from './chatRequestDtoIntegrationsInner';
import { ChatRequestDtoInput } from './chatRequestDtoInput';


export interface ChatRequestDto { 
    /**
     * Unique identifier for the model to use
     */
    model: string;
    input: ChatRequestDtoInput;
    /**
     * System prompt that sets model behaviour
     */
    system_prompt?: string;
    /**
     * Integrations (plugins / ephemeral MCP servers) to enable
     */
    integrations?: Array<ChatRequestDtoIntegrationsInner>;
    /**
     * Stream partial outputs via SSE
     */
    stream?: boolean;
    /**
     * Sampling temperature [0,1]
     */
    temperature?: number;
    /**
     * Nucleus sampling probability [0,1]
     */
    top_p?: number;
    /**
     * Top-k most probable tokens
     */
    top_k?: number;
    /**
     * Minimum base probability for token selection [0,1]
     */
    min_p?: number;
    /**
     * Repetition penalty (1 = no penalty)
     */
    repeat_penalty?: number;
    /**
     * Maximum number of tokens to generate
     */
    max_output_tokens?: number;
    /**
     * Reasoning effort level
     */
    reasoning?: ChatRequestDto.ReasoningEnum;
    /**
     * Context length in tokens (recommended to raise for MCP usage)
     */
    context_length?: number;
    /**
     * Whether to persist the chat and return a response_id
     */
    store?: boolean;
    /**
     * Previous response ID to continue a stored conversation (must start with \"resp_\")
     */
    previous_response_id?: string;
}
export namespace ChatRequestDto {
    export const ReasoningEnum = {
        Off: 'off',
        Low: 'low',
        Medium: 'medium',
        High: 'high',
        On: 'on'
    } as const;
    export type ReasoningEnum = typeof ReasoningEnum[keyof typeof ReasoningEnum];
}


