/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FunctionDto } from './functionDto';


export interface ChatCompletionNamedToolChoiceDto { 
    'function': FunctionDto;
    /**
     * For function calling, the type is always `function`.
     */
    type: ChatCompletionNamedToolChoiceDto.TypeEnum;
}
export namespace ChatCompletionNamedToolChoiceDto {
    export const TypeEnum = {
        Function: 'function'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


