/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FunctionDto } from './functionDto';
import { ChatCompletionMessageCustomToolCallDto } from './chatCompletionMessageCustomToolCallDto';
import { ChatCompletionMessageFunctionToolCallDto } from './chatCompletionMessageFunctionToolCallDto';
import { CustomDto } from './customDto';


/**
 * @type ChatCompletionAssistantMessageParamDtoToolCallsInner
 * @export
 */
export type ChatCompletionAssistantMessageParamDtoToolCallsInner = ChatCompletionMessageCustomToolCallDto | ChatCompletionMessageFunctionToolCallDto;

