/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatCompletionContentPartRefusalDto } from './chatCompletionContentPartRefusalDto';
import { ChatCompletionContentPartTextDto } from './chatCompletionContentPartTextDto';


/**
 * @type ChatCompletionAssistantMessageParamDtoContentInner
 * @export
 */
export type ChatCompletionAssistantMessageParamDtoContentInner = ChatCompletionContentPartRefusalDto | ChatCompletionContentPartTextDto | string;

