/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EphemeralMcpIntegrationDto } from './ephemeralMcpIntegrationDto';


export interface ChatMetadataDto { 
    /**
     * MongoDB ObjectId — use as chatInternalId when fetching messages
     */
    _id: string;
    name: string;
    usedModel: string;
    /**
     * ObjectId of the owning user
     */
    userId: string;
    reasoningMode: string;
    tools?: Array<EphemeralMcpIntegrationDto>;
    createdAt: string;
    updatedAt: string;
    lastMessageSentAt: string;
}

