/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatCompletionPredictionContentDto } from './chatCompletionPredictionContentDto';
import { ChatCompletionAudioParamDto } from './chatCompletionAudioParamDto';
import { ChatCompletionCreateParamsNonStreamingDtoFunctionCall } from './chatCompletionCreateParamsNonStreamingDtoFunctionCall';
import { ResponseCreateParamsNonStreamingDtoModel } from './responseCreateParamsNonStreamingDtoModel';
import { ChatCompletionCreateParamsNonStreamingDtoToolsInner } from './chatCompletionCreateParamsNonStreamingDtoToolsInner';
import { ChatCompletionCreateParamsNonStreamingDtoToolChoice } from './chatCompletionCreateParamsNonStreamingDtoToolChoice';
import { InlineU05lxdDto } from './inlineU05lxdDto';
import { WebSearchOptionsDto } from './webSearchOptionsDto';
import { ChatCompletionCreateParamsNonStreamingDtoMessagesInner } from './chatCompletionCreateParamsNonStreamingDtoMessagesInner';
import { ChatCompletionCreateParamsNonStreamingDtoResponseFormat } from './chatCompletionCreateParamsNonStreamingDtoResponseFormat';
import { ChatCompletionStreamOptionsDto } from './chatCompletionStreamOptionsDto';
import { ChatCompletionCreateParamsNonStreamingDtoStopInner } from './chatCompletionCreateParamsNonStreamingDtoStopInner';


export interface ChatCompletionCreateParamsStreamingDto { 
    /**
     * A list of messages comprising the conversation so far. Depending on the   [model](https://platform.openai.com/docs/models) you use, different message   types (modalities) are supported, like   [text](https://platform.openai.com/docs/guides/text-generation),   [images](https://platform.openai.com/docs/guides/vision), and   [audio](https://platform.openai.com/docs/guides/audio).
     */
    messages: Array<ChatCompletionCreateParamsNonStreamingDtoMessagesInner>;
    model: ResponseCreateParamsNonStreamingDtoModel;
    /**
     * Parameters for audio output. Required when audio output is requested with   `modalities: [\"audio\"]`.   [Learn more](https://platform.openai.com/docs/guides/audio).
     */
    audio?: ChatCompletionAudioParamDto;
    /**
     * Number between -2.0 and 2.0. Positive values penalize new tokens based on their   existing frequency in the text so far, decreasing the model\'s likelihood to   repeat the same line verbatim.
     */
    frequency_penalty?: number;
    function_call?: ChatCompletionCreateParamsNonStreamingDtoFunctionCall;
    functions?: Array<InlineU05lxdDto>;
    /**
     * Modify the likelihood of specified tokens appearing in the completion.      Accepts a JSON object that maps tokens (specified by their token ID in the   tokenizer) to an associated bias value from -100 to 100. Mathematically, the   bias is added to the logits generated by the model prior to sampling. The exact   effect will vary per model, but values between -1 and 1 should decrease or   increase likelihood of selection; values like -100 or 100 should result in a ban   or exclusive selection of the relevant token.
     */
    logit_bias?: object;
    /**
     * Whether to return log probabilities of the output tokens or not. If true,   returns the log probabilities of each output token returned in the `content` of   `message`.
     */
    logprobs?: object;
    /**
     * An upper bound for the number of tokens that can be generated for a completion,   including visible output tokens and   [reasoning tokens](https://platform.openai.com/docs/guides/reasoning).
     */
    max_completion_tokens?: number;
    max_tokens?: number;
    /**
     * Set of 16 key-value pairs that can be attached to an object. This can be useful   for storing additional information about the object in a structured format, and   querying for objects via API or the dashboard.      Keys are strings with a maximum length of 64 characters. Values are strings with   a maximum length of 512 characters.
     */
    metadata?: object;
    /**
     * Output types that you would like the model to generate. Most models are capable   of generating text, which is the default:      `[\"text\"]`      The `gpt-4o-audio-preview` model can also be used to   [generate audio](https://platform.openai.com/docs/guides/audio). To request that   this model generate both text and audio responses, you can use:      `[\"text\", \"audio\"]`
     */
    modalities?: Array<ChatCompletionCreateParamsStreamingDto.ModalitiesEnum>;
    /**
     * How many chat completion choices to generate for each input message. Note that   you will be charged based on the number of generated tokens across all of the   choices. Keep `n` as `1` to minimize costs.
     */
    n?: number;
    /**
     * Whether to enable   [parallel function calling](https://platform.openai.com/docs/guides/function-calling#configuring-parallel-function-calling)   during tool use.
     */
    parallel_tool_calls?: boolean;
    /**
     * Static predicted output content, such as the content of a text file that is   being regenerated.
     */
    prediction?: ChatCompletionPredictionContentDto;
    /**
     * Number between -2.0 and 2.0. Positive values penalize new tokens based on   whether they appear in the text so far, increasing the model\'s likelihood to   talk about new topics.
     */
    presence_penalty?: number;
    /**
     * Used by OpenAI to cache responses for similar requests to optimize your cache   hit rates. Replaces the `user` field.   [Learn more](https://platform.openai.com/docs/guides/prompt-caching).
     */
    prompt_cache_key?: string;
    /**
     * The retention policy for the prompt cache. Set to `24h` to enable extended   prompt caching, which keeps cached prefixes active for longer, up to a maximum   of 24 hours.   [Learn more](https://platform.openai.com/docs/guides/prompt-caching#prompt-cache-retention).
     */
    prompt_cache_retention?: ChatCompletionCreateParamsStreamingDto.PromptCacheRetentionEnum;
    /**
     * Constrains effort on reasoning for   [reasoning models](https://platform.openai.com/docs/guides/reasoning). Currently   supported values are `none`, `minimal`, `low`, `medium`, `high`, and `xhigh`.   Reducing reasoning effort can result in faster responses and fewer tokens used   on reasoning in a response.      - `gpt-5.1` defaults to `none`, which does not perform reasoning. The supported     reasoning values for `gpt-5.1` are `none`, `low`, `medium`, and `high`. Tool     calls are supported for all reasoning values in gpt-5.1.   - All models before `gpt-5.1` default to `medium` reasoning effort, and do not     support `none`.   - The `gpt-5-pro` model defaults to (and only supports) `high` reasoning effort.   - `xhigh` is supported for all models after `gpt-5.1-codex-max`.
     */
    reasoning_effort?: ChatCompletionCreateParamsStreamingDto.ReasoningEffortEnum;
    response_format?: ChatCompletionCreateParamsNonStreamingDtoResponseFormat;
    /**
     * A stable identifier used to help detect users of your application that may be   violating OpenAI\'s usage policies. The IDs should be a string that uniquely   identifies each user, with a maximum length of 64 characters. We recommend   hashing their username or email address, in order to avoid sending us any   identifying information.   [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).
     */
    safety_identifier?: string;
    seed?: number;
    /**
     * Specifies the processing type used for serving the request.      - If set to \'auto\', then the request will be processed with the service tier     configured in the Project settings. Unless otherwise configured, the Project     will use \'default\'.   - If set to \'default\', then the request will be processed with the standard     pricing and performance for the selected model.   - If set to \'[flex](https://platform.openai.com/docs/guides/flex-processing)\' or     \'[priority](https://openai.com/api-priority-processing/)\', then the request     will be processed with the corresponding service tier.   - When not set, the default behavior is \'auto\'.      When the `service_tier` parameter is set, the response body will include the   `service_tier` value based on the processing mode actually used to serve the   request. This response value may be different from the value set in the   parameter.
     */
    service_tier?: ChatCompletionCreateParamsStreamingDto.ServiceTierEnum;
    /**
     * Not supported with latest reasoning models `o3` and `o4-mini`.      Up to 4 sequences where the API will stop generating further tokens. The   returned text will not contain the stop sequence.
     */
    stop?: Array<ChatCompletionCreateParamsNonStreamingDtoStopInner>;
    /**
     * Whether or not to store the output of this chat completion request for use in   our [model distillation](https://platform.openai.com/docs/guides/distillation)   or [evals](https://platform.openai.com/docs/guides/evals) products.      Supports text and image inputs. Note: image inputs over 8MB will be dropped.
     */
    store?: object;
    /**
     * If set to true, the model response data will be streamed to the client as it is   generated using   [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format).   See the   [Streaming section below](https://platform.openai.com/docs/api-reference/chat/streaming)   for more information, along with the   [streaming responses](https://platform.openai.com/docs/guides/streaming-responses)   guide for more information on how to handle the streaming events.
     */
    stream: boolean;
    /**
     * Options for streaming response. Only set this when you set `stream: true`.
     */
    stream_options?: ChatCompletionStreamOptionsDto;
    /**
     * What sampling temperature to use, between 0 and 2. Higher values like 0.8 will   make the output more random, while lower values like 0.2 will make it more   focused and deterministic. We generally recommend altering this or `top_p` but   not both.
     */
    temperature?: number;
    tool_choice?: ChatCompletionCreateParamsNonStreamingDtoToolChoice;
    /**
     * A list of tools the model may call. You can provide either   [custom tools](https://platform.openai.com/docs/guides/function-calling#custom-tools)   or [function tools](https://platform.openai.com/docs/guides/function-calling).
     */
    tools?: Array<ChatCompletionCreateParamsNonStreamingDtoToolsInner>;
    /**
     * An integer between 0 and 20 specifying the number of most likely tokens to   return at each token position, each with an associated log probability.   `logprobs` must be set to `true` if this parameter is used.
     */
    top_logprobs?: number;
    /**
     * An alternative to sampling with temperature, called nucleus sampling, where the   model considers the results of the tokens with top_p probability mass. So 0.1   means only the tokens comprising the top 10% probability mass are considered.      We generally recommend altering this or `temperature` but not both.
     */
    top_p?: number;
    user?: string;
    /**
     * Constrains the verbosity of the model\'s response. Lower values will result in   more concise responses, while higher values will result in more verbose   responses. Currently supported values are `low`, `medium`, and `high`.
     */
    verbosity?: ChatCompletionCreateParamsStreamingDto.VerbosityEnum;
    /**
     * This tool searches the web for relevant results to use in a response. Learn more   about the   [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).
     */
    web_search_options?: WebSearchOptionsDto;
}
export namespace ChatCompletionCreateParamsStreamingDto {
    export const ModalitiesEnum = {
        Text: 'text',
        Audio: 'audio'
    } as const;
    export type ModalitiesEnum = typeof ModalitiesEnum[keyof typeof ModalitiesEnum];
    export const PromptCacheRetentionEnum = {
        InMemory: 'in-memory',
        _24h: '24h'
    } as const;
    export type PromptCacheRetentionEnum = typeof PromptCacheRetentionEnum[keyof typeof PromptCacheRetentionEnum];
    export const ReasoningEffortEnum = {
        Low: 'low',
        High: 'high',
        None: 'none',
        Minimal: 'minimal',
        Medium: 'medium',
        Xhigh: 'xhigh'
    } as const;
    export type ReasoningEffortEnum = typeof ReasoningEffortEnum[keyof typeof ReasoningEffortEnum];
    export const ServiceTierEnum = {
        Auto: 'auto',
        Default: 'default',
        Flex: 'flex',
        Scale: 'scale',
        Priority: 'priority'
    } as const;
    export type ServiceTierEnum = typeof ServiceTierEnum[keyof typeof ServiceTierEnum];
    export const VerbosityEnum = {
        Low: 'low',
        High: 'high',
        Medium: 'medium'
    } as const;
    export type VerbosityEnum = typeof VerbosityEnum[keyof typeof VerbosityEnum];
}


