/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DDto } from './dDto';


/**
 * The voice the model uses to respond. Supported built-in voices are `alloy`,   `ash`, `ballad`, `coral`, `echo`, `fable`, `nova`, `onyx`, `sage`, `shimmer`,   `marin`, and `cedar`. You may also provide a custom voice object with an `id`,   for example `{ \"id\": \"voice_1234\" }`.
 */
/**
 * @type ChatCompletionAudioParamDtoVoice
 * The voice the model uses to respond. Supported built-in voices are `alloy`,   `ash`, `ballad`, `coral`, `echo`, `fable`, `nova`, `onyx`, `sage`, `shimmer`,   `marin`, and `cedar`. You may also provide a custom voice object with an `id`,   for example `{ \"id\": \"voice_1234\" }`.
 * @export
 */
export type ChatCompletionAudioParamDtoVoice = DDto | string;

