/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomDto } from './customDto';


export interface ChatCompletionNamedToolChoiceCustomDto { 
    custom: CustomDto;
    /**
     * For custom tool calling, the type is always `custom`.
     */
    type: ChatCompletionNamedToolChoiceCustomDto.TypeEnum;
}
export namespace ChatCompletionNamedToolChoiceCustomDto {
    export const TypeEnum = {
        Custom: 'custom'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


