/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseFormatTextDto } from './responseFormatTextDto';
import { JSONSchemaDto } from './jSONSchemaDto';
import { ResponseFormatJSONSchemaDto } from './responseFormatJSONSchemaDto';
import { ResponseFormatJSONObjectDto } from './responseFormatJSONObjectDto';


/**
 * An object specifying the format that the model must output.      Setting to `{ \"type\": \"json_schema\", \"json_schema\": {...} }` enables Structured   Outputs which ensures the model will match your supplied JSON schema. Learn more   in the   [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).      Setting to `{ \"type\": \"json_object\" }` enables the older JSON mode, which   ensures the message the model generates is valid JSON. Using `json_schema` is   preferred for models that support it.
 */
/**
 * @type ChatCompletionCreateParamsNonStreamingDtoResponseFormat
 * An object specifying the format that the model must output.      Setting to `{ \"type\": \"json_schema\", \"json_schema\": {...} }` enables Structured   Outputs which ensures the model will match your supplied JSON schema. Learn more   in the   [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).      Setting to `{ \"type\": \"json_object\" }` enables the older JSON mode, which   ensures the message the model generates is valid JSON. Using `json_schema` is   preferred for models that support it.
 * @export
 */
export type ChatCompletionCreateParamsNonStreamingDtoResponseFormat = ResponseFormatJSONObjectDto | ResponseFormatJSONSchemaDto | ResponseFormatTextDto;

