/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FunctionDefinitionDto } from './functionDefinitionDto';


export interface ChatCompletionFunctionToolDto { 
    'function': FunctionDefinitionDto;
    /**
     * The type of the tool. Currently, only `function` is supported.
     */
    type: ChatCompletionFunctionToolDto.TypeEnum;
}
export namespace ChatCompletionFunctionToolDto {
    export const TypeEnum = {
        Function: 'function'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


