/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomDto } from './customDto';


export interface ChatCompletionCustomToolDto { 
    /**
     * Properties of the custom tool.
     */
    custom: CustomDto;
    /**
     * The type of the custom tool. Always `custom`.
     */
    type: ChatCompletionCustomToolDto.TypeEnum;
}
export namespace ChatCompletionCustomToolDto {
    export const TypeEnum = {
        Custom: 'custom'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


