/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatCompletionAllowedToolsDto { 
    /**
     * Constrains the tools available to the model to a pre-defined set.      `auto` allows the model to pick from among the allowed tools and generate a   message.      `required` requires the model to call one or more of the allowed tools.
     */
    mode: ChatCompletionAllowedToolsDto.ModeEnum;
    /**
     * A list of tool definitions that the model should be allowed to call.      For the Chat Completions API, the list of tool definitions might look like:      ```json   [     { \"type\": \"function\", \"function\": { \"name\": \"get_weather\" } },     { \"type\": \"function\", \"function\": { \"name\": \"get_time\" } }   ]   ```
     */
    tools: Array<Array<string>>;
}
export namespace ChatCompletionAllowedToolsDto {
    export const ModeEnum = {
        Auto: 'auto',
        Required: 'required'
    } as const;
    export type ModeEnum = typeof ModeEnum[keyof typeof ModeEnum];
}


