/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatCompletionContentPartTextDto } from './chatCompletionContentPartTextDto';


/**
 * @type ChatCompletionDeveloperMessageParamDtoContentInner
 * @export
 */
export type ChatCompletionDeveloperMessageParamDtoContentInner = ChatCompletionContentPartTextDto | string;

