/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatRequestDtoInputOneOfInner } from './chatRequestDtoInputOneOfInner';


/**
 * Message(s) to send to the model
 */
/**
 * @type ChatRequestDtoInput
 * Message(s) to send to the model
 * @export
 */
export type ChatRequestDtoInput = Array<ChatRequestDtoInputOneOfInner> | string;

