/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatCompletionDeveloperMessageParamDtoContentInner } from './chatCompletionDeveloperMessageParamDtoContentInner';


export interface ChatCompletionDeveloperMessageParamDto { 
    /**
     * The contents of the developer message.
     */
    content: Array<ChatCompletionDeveloperMessageParamDtoContentInner>;
    /**
     * The role of the messages author, in this case `developer`.
     */
    role: ChatCompletionDeveloperMessageParamDto.RoleEnum;
    /**
     * An optional name for the participant. Provides the model information to   differentiate between participants of the same role.
     */
    name?: string;
}
export namespace ChatCompletionDeveloperMessageParamDto {
    export const RoleEnum = {
        Developer: 'developer'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


