/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogprobsDto } from './logprobsDto';
import { ChatCompletionMessageDto } from './chatCompletionMessageDto';


export interface ChoiceDto { 
    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model   hit a natural stop point or a provided stop sequence, `length` if the maximum   number of tokens specified in the request was reached, `content_filter` if   content was omitted due to a flag from our content filters, `tool_calls` if the   model called a tool, or `function_call` (deprecated) if the model called a   function.
     */
    finish_reason: ChoiceDto.FinishReasonEnum;
    /**
     * The index of the choice in the list of choices.
     */
    index: number;
    /**
     * Log probability information for the choice.
     */
    logprobs: LogprobsDto;
    /**
     * A chat completion message generated by the model.
     */
    message: ChatCompletionMessageDto;
}
export namespace ChoiceDto {
    export const FinishReasonEnum = {
        Stop: 'stop',
        Length: 'length',
        ToolCalls: 'tool_calls',
        ContentFilter: 'content_filter',
        FunctionCall: 'function_call'
    } as const;
    export type FinishReasonEnum = typeof FinishReasonEnum[keyof typeof FinishReasonEnum];
}


