/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodeInterpreterDtoContainer } from './codeInterpreterDtoContainer';


export interface CodeInterpreterDto { 
    container: CodeInterpreterDtoContainer;
    /**
     * The type of the code interpreter tool. Always `code_interpreter`.
     */
    type: CodeInterpreterDto.TypeEnum;
}
export namespace CodeInterpreterDto {
    export const TypeEnum = {
        CodeInterpreter: 'code_interpreter'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


