/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AcknowledgedSafetyCheckDto } from './acknowledgedSafetyCheckDto';
import { ResponseComputerToolCallOutputScreenshotDto } from './responseComputerToolCallOutputScreenshotDto';


export interface ComputerCallOutputDto { 
    /**
     * The ID of the computer tool call that produced the output.
     */
    call_id: string;
    /**
     * A computer screenshot image used with the computer use tool.
     */
    output: ResponseComputerToolCallOutputScreenshotDto;
    /**
     * The type of the computer tool call output. Always `computer_call_output`.
     */
    type: ComputerCallOutputDto.TypeEnum;
    /**
     * The ID of the computer tool call output.
     */
    id?: string;
    /**
     * The safety checks reported by the API that have been acknowledged by the   developer.
     */
    acknowledged_safety_checks?: Array<AcknowledgedSafetyCheckDto>;
    /**
     * The status of the message input. One of `in_progress`, `completed`, or   `incomplete`. Populated when input items are returned via API.
     */
    status?: ComputerCallOutputDto.StatusEnum;
}
export namespace ComputerCallOutputDto {
    export const TypeEnum = {
        ComputerCallOutput: 'computer_call_output'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const StatusEnum = {
        InProgress: 'in_progress',
        Completed: 'completed',
        Incomplete: 'incomplete'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


