/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompoundFilterDto { 
    /**
     * Array of filters to combine. Items can be `ComparisonFilter` or   `CompoundFilter`.
     */
    filters: Array<Array<string>>;
    /**
     * Type of operation: `and` or `or`.
     */
    type: CompoundFilterDto.TypeEnum;
}
export namespace CompoundFilterDto {
    export const TypeEnum = {
        And: 'and',
        Or: 'or'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


