/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ComputerToolDto { 
    /**
     * The type of the computer tool. Always `computer`.
     */
    type: ComputerToolDto.TypeEnum;
}
export namespace ComputerToolDto {
    export const TypeEnum = {
        Computer: 'computer'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


