/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatCompletionCreateParamsStreamingDto } from './chatCompletionCreateParamsStreamingDto';
import { ChatCompletionPredictionContentDto } from './chatCompletionPredictionContentDto';
import { ChatCompletionAudioParamDto } from './chatCompletionAudioParamDto';
import { ChatCompletionCreateParamsNonStreamingDtoFunctionCall } from './chatCompletionCreateParamsNonStreamingDtoFunctionCall';
import { ChatCompletionCreateParamsNonStreamingDtoToolChoice } from './chatCompletionCreateParamsNonStreamingDtoToolChoice';
import { WebSearchOptionsDto } from './webSearchOptionsDto';
import { ChatCompletionCreateParamsNonStreamingDto } from './chatCompletionCreateParamsNonStreamingDto';
import { ChatCompletionCreateParamsNonStreamingDtoResponseFormat } from './chatCompletionCreateParamsNonStreamingDtoResponseFormat';
import { ChatCompletionStreamOptionsDto } from './chatCompletionStreamOptionsDto';
import { ResponseCreateParamsNonStreamingDtoModel } from './responseCreateParamsNonStreamingDtoModel';
import { ChatCompletionCreateParamsNonStreamingDtoToolsInner } from './chatCompletionCreateParamsNonStreamingDtoToolsInner';
import { InlineU05lxdDto } from './inlineU05lxdDto';
import { ChatCompletionCreateParamsNonStreamingDtoMessagesInner } from './chatCompletionCreateParamsNonStreamingDtoMessagesInner';
import { ChatCompletionCreateParamsNonStreamingDtoStopInner } from './chatCompletionCreateParamsNonStreamingDtoStopInner';


/**
 * @type CompletionsStreamOpenAiRequest
 * @export
 */
export type CompletionsStreamOpenAiRequest = ChatCompletionCreateParamsNonStreamingDto | ChatCompletionCreateParamsStreamingDto;

