/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComparisonFilterDtoValueInner } from './comparisonFilterDtoValueInner';


export interface ComparisonFilterDto { 
    /**
     * The key to compare against the value.
     */
    key: string;
    /**
     * Specifies the comparison operator: `eq`, `ne`, `gt`, `gte`, `lt`, `lte`, `in`,   `nin`.      - `eq`: equals   - `ne`: not equal   - `gt`: greater than   - `gte`: greater than or equal   - `lt`: less than   - `lte`: less than or equal   - `in`: in   - `nin`: not in
     */
    type: ComparisonFilterDto.TypeEnum;
    /**
     * The value to compare against the attribute key; supports string, number, or   boolean types.
     */
    value: Array<ComparisonFilterDtoValueInner>;
}
export namespace ComparisonFilterDto {
    export const TypeEnum = {
        Eq: 'eq',
        Ne: 'ne',
        Gt: 'gt',
        Gte: 'gte',
        Lt: 'lt',
        Lte: 'lte',
        In: 'in',
        Nin: 'nin'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


