/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContainerReferenceDto { 
    /**
     * The ID of the referenced container.
     */
    container_id: string;
    /**
     * References a container created with the /v1/containers endpoint
     */
    type: ContainerReferenceDto.TypeEnum;
}
export namespace ContainerReferenceDto {
    export const TypeEnum = {
        ContainerReference: 'container_reference'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


