/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineSkillDto } from './inlineSkillDto';
import { SkillReferenceDto } from './skillReferenceDto';
import { InlineSkillSourceDto } from './inlineSkillSourceDto';


/**
 * @type ContainerAutoDtoSkillsInner
 * @export
 */
export type ContainerAutoDtoSkillsInner = InlineSkillDto | SkillReferenceDto;

