/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EphemeralMcpIntegrationDto } from './ephemeralMcpIntegrationDto';


export interface CreateChatMetadataDto { 
    /**
     * Human-readable name for this chat session
     */
    name: string;
    /**
     * LLM model identifier used in this session
     */
    usedModel: string;
    client: CreateChatMetadataDto.ClientEnum;
    /**
     * Reasoning mode (e.g. off / low / medium / high / on)
     */
    reasoningMode: string;
    /**
     * MCP integrations to associate with this session
     */
    tools?: Array<EphemeralMcpIntegrationDto>;
    useCrypto?: boolean;
    cryptoKey?: string;
}
export namespace CreateChatMetadataDto {
    export const ClientEnum = {
        Openai: 'OPENAI',
        Lmstudio: 'LMSTUDIO'
    } as const;
    export type ClientEnum = typeof ClientEnum[keyof typeof ClientEnum];
}


