/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTokenLimitConfigDto { 
    minutesTillReset: number;
    tokensPerIntervall: number;
    subscription: CreateTokenLimitConfigDto.SubscriptionEnum;
}
export namespace CreateTokenLimitConfigDto {
    export const SubscriptionEnum = {
        Free: 'free',
        Basic: 'basic'
    } as const;
    export type SubscriptionEnum = typeof SubscriptionEnum[keyof typeof SubscriptionEnum];
}


