/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrammarDto } from './grammarDto';
import { TextDto } from './textDto';


/**
 * The input format for the custom tool. Default is unconstrained text.
 */
/**
 * @type CustomToolDtoFormat
 * The input format for the custom tool. Default is unconstrained text.
 * @export
 */
export type CustomToolDtoFormat = GrammarDto | TextDto;

