/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeleteFileDto { 
    /**
     * Path of the file to delete relative to the workspace root.
     */
    path: string;
    /**
     * The operation type. Always `delete_file`.
     */
    type: DeleteFileDto.TypeEnum;
}
export namespace DeleteFileDto {
    export const TypeEnum = {
        DeleteFile: 'delete_file'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


