/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PathDto } from './pathDto';


export interface DragDto { 
    /**
     * An array of coordinates representing the path of the drag action. Coordinates   will appear as an array of objects, eg      ```   [     { x: 100, y: 200 },     { x: 200, y: 300 }   ]   ```
     */
    path: Array<PathDto>;
    /**
     * Specifies the event type. For a drag action, this property is always set to   `drag`.
     */
    type: DragDto.TypeEnum;
    /**
     * The keys being held while dragging the mouse.
     */
    keys?: Array<string>;
}
export namespace DragDto {
    export const TypeEnum = {
        Drag: 'drag'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


