/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileSearchToolDtoFilters } from './fileSearchToolDtoFilters';
import { RankingOptionsDto } from './rankingOptionsDto';


export interface FileSearchToolDto { 
    /**
     * The type of the file search tool. Always `file_search`.
     */
    type: FileSearchToolDto.TypeEnum;
    /**
     * The IDs of the vector stores to search.
     */
    vector_store_ids: Array<string>;
    filters?: FileSearchToolDtoFilters;
    /**
     * The maximum number of results to return. This number should be between 1 and 50   inclusive.
     */
    max_num_results?: number;
    /**
     * Ranking options for search.
     */
    ranking_options?: RankingOptionsDto;
}
export namespace FileSearchToolDto {
    export const TypeEnum = {
        FileSearch: 'file_search'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


