/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FilePathDto { 
    /**
     * The ID of the file.
     */
    file_id: string;
    /**
     * The index of the file in the list of files.
     */
    index: number;
    /**
     * The type of the file path. Always `file_path`.
     */
    type: FilePathDto.TypeEnum;
}
export namespace FilePathDto {
    export const TypeEnum = {
        FilePath: 'file_path'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


