/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileDto { 
    file: FileDto;
    /**
     * The type of the content part. Always `file`.
     */
    type: FileDto.TypeEnum;
}
export namespace FileDto {
    export const TypeEnum = {
        File: 'file'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


