/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComparisonFilterDtoValueInner } from './comparisonFilterDtoValueInner';
import { CompoundFilterDto } from './compoundFilterDto';
import { ComparisonFilterDto } from './comparisonFilterDto';


/**
 * A filter to apply.
 */
/**
 * @type FileSearchToolDtoFilters
 * A filter to apply.
 * @export
 */
export type FileSearchToolDtoFilters = ComparisonFilterDto | CompoundFilterDto;

