/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FiltersDto { 
    /**
     * Allowed domains for the search. If not provided, all domains are allowed.   Subdomains of the provided domains are allowed as well.      Example: `[\"pubmed.ncbi.nlm.nih.gov\"]`
     */
    allowed_domains?: Array<string>;
}

