/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The image generation model to use. Default: `gpt-image-1`.
 */
/**
 * @type ImageGenerationDtoModel
 * The image generation model to use. Default: `gpt-image-1`.
 * @export
 */
export type ImageGenerationDtoModel = object | string;

