/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImageInputDto { 
    type: ImageInputDto.TypeEnum;
    /**
     * Base64-encoded data URL of the image
     */
    data_url: string;
}
export namespace ImageInputDto {
    export const TypeEnum = {
        Image: 'image'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


