/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IncompleteDetailsDto { 
    /**
     * The reason why the response is incomplete.
     */
    reason?: IncompleteDetailsDto.ReasonEnum;
}
export namespace IncompleteDetailsDto {
    export const ReasonEnum = {
        MaxOutputTokens: 'max_output_tokens',
        ContentFilter: 'content_filter'
    } as const;
    export type ReasonEnum = typeof ReasonEnum[keyof typeof ReasonEnum];
}


