/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineSkillSourceDto { 
    /**
     * Base64-encoded skill zip bundle.
     */
    data: string;
    /**
     * The media type of the inline skill payload. Must be `application/zip`.
     */
    media_type: InlineSkillSourceDto.MediaTypeEnum;
    /**
     * The type of the inline skill source. Must be `base64`.
     */
    type: InlineSkillSourceDto.TypeEnum;
}
export namespace InlineSkillSourceDto {
    export const MediaTypeEnum = {
        ApplicationZip: 'application/zip'
    } as const;
    export type MediaTypeEnum = typeof MediaTypeEnum[keyof typeof MediaTypeEnum];
    export const TypeEnum = {
        Base64: 'base64'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


