/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LocalShellDto { 
    /**
     * The type of the local shell tool. Always `local_shell`.
     */
    type: LocalShellDto.TypeEnum;
}
export namespace LocalShellDto {
    export const TypeEnum = {
        LocalShell: 'local_shell'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


