/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocalSkillDto } from './localSkillDto';


export interface LocalEnvironmentDto { 
    /**
     * Use a local computer environment.
     */
    type: LocalEnvironmentDto.TypeEnum;
    /**
     * An optional list of skills.
     */
    skills?: Array<LocalSkillDto>;
}
export namespace LocalEnvironmentDto {
    export const TypeEnum = {
        Local: 'local'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


