/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionDto } from './actionDto';


export interface LocalShellCallDto { 
    /**
     * The unique ID of the local shell call.
     */
    id: string;
    /**
     * Execute a shell command on the server.
     */
    action: ActionDto;
    /**
     * The unique ID of the local shell tool call generated by the model.
     */
    call_id: string;
    /**
     * The status of the local shell call.
     */
    status: LocalShellCallDto.StatusEnum;
    /**
     * The type of the local shell call. Always `local_shell_call`.
     */
    type: LocalShellCallDto.TypeEnum;
}
export namespace LocalShellCallDto {
    export const StatusEnum = {
        InProgress: 'in_progress',
        Completed: 'completed',
        Incomplete: 'incomplete'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const TypeEnum = {
        LocalShellCall: 'local_shell_call'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


