/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TopLogprobDto } from './topLogprobDto';


export interface LogprobDto { 
    token: string;
    bytes: Array<number>;
    logprob: number;
    top_logprobs: Array<TopLogprobDto>;
}

