/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogsDto { 
    /**
     * The logs output from the code interpreter.
     */
    logs: string;
    /**
     * The type of the output. Always `logs`.
     */
    type: LogsDto.TypeEnum;
}
export namespace LogsDto {
    export const TypeEnum = {
        Logs: 'logs'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


