/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { McpToolApprovalFilterDto } from './mcpToolApprovalFilterDto';
import { NeverDto } from './neverDto';
import { AlwaysDto } from './alwaysDto';


/**
 * Specify which of the MCP server\'s tools require approval.
 */
/**
 * @type McpDtoRequireApproval
 * Specify which of the MCP server\'s tools require approval.
 * @export
 */
export type McpDtoRequireApproval = McpToolApprovalFilterDto | string;

