/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageDtoContentInner } from './messageDtoContentInner';


export interface MessageDto { 
    /**
     * A list of one or many input items to the model, containing different content   types.
     */
    content: Array<MessageDtoContentInner>;
    /**
     * The role of the message input. One of `user`, `system`, or `developer`.
     */
    role: MessageDto.RoleEnum;
    /**
     * The status of item. One of `in_progress`, `completed`, or `incomplete`.   Populated when items are returned via API.
     */
    status?: MessageDto.StatusEnum;
    /**
     * The type of the message input. Always set to `message`.
     */
    type?: MessageDto.TypeEnum;
}
export namespace MessageDto {
    export const RoleEnum = {
        User: 'user',
        System: 'system',
        Developer: 'developer'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
    export const StatusEnum = {
        InProgress: 'in_progress',
        Completed: 'completed',
        Incomplete: 'incomplete'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const TypeEnum = {
        Message: 'message'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


