/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseInputImageDto } from './responseInputImageDto';
import { ResponseInputFileDto } from './responseInputFileDto';
import { ResponseInputTextDto } from './responseInputTextDto';


/**
 * @type MessageDtoContentInner
 * @export
 */
export type MessageDtoContentInner = ResponseInputFileDto | ResponseInputImageDto | ResponseInputTextDto;

