/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Inline6nksgqDto } from './inline6nksgqDto';
import { CustomToolDto } from './customToolDto';
import { CustomToolDtoFormat } from './customToolDtoFormat';


/**
 * @type NamespaceToolDtoToolsInner
 * @export
 */
export type NamespaceToolDtoToolsInner = CustomToolDto | Inline6nksgqDto;

