/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NamespaceToolDtoToolsInner } from './namespaceToolDtoToolsInner';


export interface NamespaceToolDto { 
    /**
     * A description of the namespace shown to the model.
     */
    description: string;
    /**
     * The namespace name used in tool calls (for example, `crm`).
     */
    name: string;
    /**
     * The function/custom tools available inside this namespace.
     */
    tools: Array<NamespaceToolDtoToolsInner>;
    /**
     * The type of the tool. Always `namespace`.
     */
    type: NamespaceToolDto.TypeEnum;
}
export namespace NamespaceToolDto {
    export const TypeEnum = {
        Namespace: 'namespace'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


