/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OpenPageDto { 
    /**
     * The action type.
     */
    type: OpenPageDto.TypeEnum;
    /**
     * The URL opened by the model.
     */
    url?: string;
}
export namespace OpenPageDto {
    export const TypeEnum = {
        OpenPage: 'open_page'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


