/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExitDto } from './exitDto';
import { TimeoutDto } from './timeoutDto';


/**
 * Represents either an exit outcome (with an exit code) or a timeout outcome for a   shell call output chunk.
 */
/**
 * @type OutputDtoOutcome
 * Represents either an exit outcome (with an exit code) or a timeout outcome for a   shell call output chunk.
 * @export
 */
export type OutputDtoOutcome = ExitDto | TimeoutDto;

