/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OutputDtoOutcome } from './outputDtoOutcome';


export interface OutputDto { 
    outcome: OutputDtoOutcome;
    /**
     * The standard error output that was captured.
     */
    stderr: string;
    /**
     * The standard output that was captured.
     */
    stdout: string;
    /**
     * The identifier of the actor that created the item.
     */
    created_by?: string;
}

