/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PromptTokensDetailsDto { 
    /**
     * Audio input tokens present in the prompt.
     */
    audio_tokens?: number;
    /**
     * Cached tokens present in the prompt.
     */
    cached_tokens?: number;
}

