/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProviderInfoDto { 
    type: ProviderInfoDto.TypeEnum;
    plugin_id?: string;
    server_label?: string;
}
export namespace ProviderInfoDto {
    export const TypeEnum = {
        Plugin: 'plugin',
        EphemeralMcp: 'ephemeral_mcp'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


