/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HybridSearchDto } from './hybridSearchDto';


export interface RankingOptionsDto { 
    /**
     * Weights that control how reciprocal rank fusion balances semantic embedding   matches versus sparse keyword matches when hybrid search is enabled.
     */
    hybrid_search?: HybridSearchDto;
    /**
     * The ranker to use for the file search.
     */
    ranker?: RankingOptionsDto.RankerEnum;
    /**
     * The score threshold for the file search, a number between 0 and 1. Numbers   closer to 1 will attempt to return only the most relevant results, but may   return fewer results.
     */
    score_threshold?: number;
}
export namespace RankingOptionsDto {
    export const RankerEnum = {
        Auto: 'auto',
        Default20241115: 'default-2024-11-15'
    } as const;
    export type RankerEnum = typeof RankerEnum[keyof typeof RankerEnum];
}


