/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReasoningOutputDto { 
    type: ReasoningOutputDto.TypeEnum;
    content: string;
}
export namespace ReasoningOutputDto {
    export const TypeEnum = {
        Reasoning: 'reasoning'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


