/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseMcpCallInProgressEventDto { 
    /**
     * The unique identifier of the MCP tool call item being processed.
     */
    item_id: string;
    /**
     * The index of the output item in the response\'s output array.
     */
    output_index: number;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always \'response.mcp_call.in_progress\'.
     */
    type: ResponseMcpCallInProgressEventDto.TypeEnum;
}
export namespace ResponseMcpCallInProgressEventDto {
    export const TypeEnum = {
        ResponseMcpCallInProgress: 'response.mcp_call.in_progress'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


