/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseOutputTextAnnotationAddedEventDto { 
    /**
     * The annotation object being added. (See annotation schema for details.)
     */
    annotation: object;
    /**
     * The index of the annotation within the content part.
     */
    annotation_index: number;
    /**
     * The index of the content part within the output item.
     */
    content_index: number;
    /**
     * The unique identifier of the item to which the annotation is being added.
     */
    item_id: string;
    /**
     * The index of the output item in the response\'s output array.
     */
    output_index: number;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always \'response.output_text.annotation.added\'.
     */
    type: ResponseOutputTextAnnotationAddedEventDto.TypeEnum;
}
export namespace ResponseOutputTextAnnotationAddedEventDto {
    export const TypeEnum = {
        ResponseOutputTextAnnotationAdded: 'response.output_text.annotation.added'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


