/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InputTokensDetailsDto } from './inputTokensDetailsDto';
import { OutputTokensDetailsDto } from './outputTokensDetailsDto';


export interface ResponseUsageDto { 
    /**
     * The number of input tokens.
     */
    input_tokens: number;
    /**
     * A detailed breakdown of the input tokens.
     */
    input_tokens_details: InputTokensDetailsDto;
    /**
     * The number of output tokens.
     */
    output_tokens: number;
    /**
     * A detailed breakdown of the output tokens.
     */
    output_tokens_details: OutputTokensDetailsDto;
    /**
     * The total number of tokens used.
     */
    total_tokens: number;
}

