/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseCodeInterpreterToolCallDtoOutputsInner } from './responseCodeInterpreterToolCallDtoOutputsInner';


export interface ResponseCodeInterpreterToolCallDto { 
    /**
     * The unique ID of the code interpreter tool call.
     */
    id: string;
    /**
     * The code to run, or null if not available.
     */
    code: string;
    /**
     * The ID of the container used to run the code.
     */
    container_id: string;
    /**
     * The outputs generated by the code interpreter, such as logs or images. Can be   null if no outputs are available.
     */
    outputs: Array<ResponseCodeInterpreterToolCallDtoOutputsInner>;
    /**
     * The status of the code interpreter tool call. Valid values are `in_progress`,   `completed`, `incomplete`, `interpreting`, and `failed`.
     */
    status: ResponseCodeInterpreterToolCallDto.StatusEnum;
    /**
     * The type of the code interpreter tool call. Always `code_interpreter_call`.
     */
    type: ResponseCodeInterpreterToolCallDto.TypeEnum;
}
export namespace ResponseCodeInterpreterToolCallDto {
    export const StatusEnum = {
        InProgress: 'in_progress',
        Completed: 'completed',
        Incomplete: 'incomplete',
        Failed: 'failed',
        Interpreting: 'interpreting'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const TypeEnum = {
        CodeInterpreterCall: 'code_interpreter_call'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


