/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseFunctionCallArgumentsDoneEventDto { 
    /**
     * The function-call arguments.
     */
    arguments: string;
    /**
     * The ID of the item.
     */
    item_id: string;
    /**
     * The name of the function that was called.
     */
    name: string;
    /**
     * The index of the output item.
     */
    output_index: number;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    type: ResponseFunctionCallArgumentsDoneEventDto.TypeEnum;
}
export namespace ResponseFunctionCallArgumentsDoneEventDto {
    export const TypeEnum = {
        ResponseFunctionCallArgumentsDone: 'response.function_call_arguments.done'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


