/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseOutputTextDto } from './responseOutputTextDto';
import { LogprobDto } from './logprobDto';
import { ResponseOutputRefusalDto } from './responseOutputRefusalDto';
import { ResponseOutputTextDtoAnnotationsInner } from './responseOutputTextDtoAnnotationsInner';


/**
 * @type ResponseOutputMessageDtoContentInner
 * @export
 */
export type ResponseOutputMessageDtoContentInner = ResponseOutputRefusalDto | ResponseOutputTextDto;

