/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseOutputItemAddedEventDtoItem } from './responseOutputItemAddedEventDtoItem';


export interface ResponseOutputItemAddedEventDto { 
    item: ResponseOutputItemAddedEventDtoItem;
    /**
     * The index of the output item that was added.
     */
    output_index: number;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always `response.output_item.added`.
     */
    type: ResponseOutputItemAddedEventDto.TypeEnum;
}
export namespace ResponseOutputItemAddedEventDto {
    export const TypeEnum = {
        ResponseOutputItemAdded: 'response.output_item.added'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


