/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseReasoningSummaryTextDeltaEventDto { 
    /**
     * The text delta that was added to the summary.
     */
    delta: string;
    /**
     * The ID of the item this summary text delta is associated with.
     */
    item_id: string;
    /**
     * The index of the output item this summary text delta is associated with.
     */
    output_index: number;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The index of the summary part within the reasoning summary.
     */
    summary_index: number;
    /**
     * The type of the event. Always `response.reasoning_summary_text.delta`.
     */
    type: ResponseReasoningSummaryTextDeltaEventDto.TypeEnum;
}
export namespace ResponseReasoningSummaryTextDeltaEventDto {
    export const TypeEnum = {
        ResponseReasoningSummaryTextDelta: 'response.reasoning_summary_text.delta'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


