/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseImageGenCallCompletedEventDto { 
    /**
     * The unique identifier of the image generation item being processed.
     */
    item_id: string;
    /**
     * The index of the output item in the response\'s output array.
     */
    output_index: number;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always \'response.image_generation_call.completed\'.
     */
    type: ResponseImageGenCallCompletedEventDto.TypeEnum;
}
export namespace ResponseImageGenCallCompletedEventDto {
    export const TypeEnum = {
        ResponseImageGenerationCallCompleted: 'response.image_generation_call.completed'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


