/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseToolSearchCallDto { 
    /**
     * The unique ID of the tool search call item.
     */
    id: string;
    /**
     * Arguments used for the tool search call.
     */
    arguments: object;
    /**
     * The unique ID of the tool search call generated by the model.
     */
    call_id: string;
    /**
     * Whether tool search was executed by the server or by the client.
     */
    execution: ResponseToolSearchCallDto.ExecutionEnum;
    /**
     * The status of the tool search call item that was recorded.
     */
    status: ResponseToolSearchCallDto.StatusEnum;
    /**
     * The type of the item. Always `tool_search_call`.
     */
    type: ResponseToolSearchCallDto.TypeEnum;
    /**
     * The identifier of the actor that created the item.
     */
    created_by?: string;
}
export namespace ResponseToolSearchCallDto {
    export const ExecutionEnum = {
        Server: 'server',
        Client: 'client'
    } as const;
    export type ExecutionEnum = typeof ExecutionEnum[keyof typeof ExecutionEnum];
    export const StatusEnum = {
        InProgress: 'in_progress',
        Completed: 'completed',
        Incomplete: 'incomplete'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const TypeEnum = {
        ToolSearchCall: 'tool_search_call'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


