/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionDto } from './actionDto';
import { ResponseFunctionShellToolCallDtoEnvironment } from './responseFunctionShellToolCallDtoEnvironment';


export interface ResponseFunctionShellToolCallDto { 
    /**
     * The unique ID of the shell tool call. Populated when this item is returned via   API.
     */
    id: string;
    /**
     * The shell commands and limits that describe how to run the tool call.
     */
    action: ActionDto;
    /**
     * The unique ID of the shell tool call generated by the model.
     */
    call_id: string;
    environment: ResponseFunctionShellToolCallDtoEnvironment;
    /**
     * The status of the shell call. One of `in_progress`, `completed`, or   `incomplete`.
     */
    status: ResponseFunctionShellToolCallDto.StatusEnum;
    /**
     * The type of the item. Always `shell_call`.
     */
    type: ResponseFunctionShellToolCallDto.TypeEnum;
    /**
     * The ID of the entity that created this tool call.
     */
    created_by?: string;
}
export namespace ResponseFunctionShellToolCallDto {
    export const StatusEnum = {
        InProgress: 'in_progress',
        Completed: 'completed',
        Incomplete: 'incomplete'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const TypeEnum = {
        ShellCall: 'shell_call'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


