/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseContentPartDoneEventDtoPart } from './responseContentPartDoneEventDtoPart';


export interface ResponseContentPartDoneEventDto { 
    /**
     * The index of the content part that is done.
     */
    content_index: number;
    /**
     * The ID of the output item that the content part was added to.
     */
    item_id: string;
    /**
     * The index of the output item that the content part was added to.
     */
    output_index: number;
    part: ResponseContentPartDoneEventDtoPart;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always `response.content_part.done`.
     */
    type: ResponseContentPartDoneEventDto.TypeEnum;
}
export namespace ResponseContentPartDoneEventDto {
    export const TypeEnum = {
        ResponseContentPartDone: 'response.content_part.done'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


