/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseReasoningTextDoneEventDto { 
    /**
     * The index of the reasoning content part.
     */
    content_index: number;
    /**
     * The ID of the item this reasoning text is associated with.
     */
    item_id: string;
    /**
     * The index of the output item this reasoning text is associated with.
     */
    output_index: number;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The full text of the completed reasoning content.
     */
    text: string;
    /**
     * The type of the event. Always `response.reasoning_text.done`.
     */
    type: ResponseReasoningTextDoneEventDto.TypeEnum;
}
export namespace ResponseReasoningTextDoneEventDto {
    export const TypeEnum = {
        ResponseReasoningTextDone: 'response.reasoning_text.done'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


