/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseDto } from './responseDto';


export interface ResponseInProgressEventDto { 
    /**
     * The response that is in progress.
     */
    response: ResponseDto;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always `response.in_progress`.
     */
    type: ResponseInProgressEventDto.TypeEnum;
}
export namespace ResponseInProgressEventDto {
    export const TypeEnum = {
        ResponseInProgress: 'response.in_progress'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


