/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseDto } from './responseDto';


export interface ResponseQueuedEventDto { 
    /**
     * The full response object that is queued.
     */
    response: ResponseDto;
    /**
     * The sequence number for this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always \'response.queued\'.
     */
    type: ResponseQueuedEventDto.TypeEnum;
}
export namespace ResponseQueuedEventDto {
    export const TypeEnum = {
        ResponseQueued: 'response.queued'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


