/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseCompactionItemDto { 
    /**
     * The unique ID of the compaction item.
     */
    id: string;
    /**
     * The encrypted content that was produced by compaction.
     */
    encrypted_content: string;
    /**
     * The type of the item. Always `compaction`.
     */
    type: ResponseCompactionItemDto.TypeEnum;
    /**
     * The identifier of the actor that created the item.
     */
    created_by?: string;
}
export namespace ResponseCompactionItemDto {
    export const TypeEnum = {
        Compaction: 'compaction'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


