/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseInputImageDto { 
    /**
     * The detail level of the image to be sent to the model. One of `high`, `low`,   `auto`, or `original`. Defaults to `auto`.
     */
    detail: ResponseInputImageDto.DetailEnum;
    /**
     * The type of the input item. Always `input_image`.
     */
    type: ResponseInputImageDto.TypeEnum;
    /**
     * The ID of the file to be sent to the model.
     */
    file_id?: string;
    /**
     * The URL of the image to be sent to the model. A fully qualified URL or base64   encoded image in a data URL.
     */
    image_url?: string;
}
export namespace ResponseInputImageDto {
    export const DetailEnum = {
        Low: 'low',
        High: 'high',
        Auto: 'auto',
        Original: 'original'
    } as const;
    export type DetailEnum = typeof DetailEnum[keyof typeof DetailEnum];
    export const TypeEnum = {
        InputImage: 'input_image'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


