/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseMcpListToolsInProgressEventDto { 
    /**
     * The ID of the MCP tool call item that is being processed.
     */
    item_id: string;
    /**
     * The index of the output item that is being processed.
     */
    output_index: number;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always \'response.mcp_list_tools.in_progress\'.
     */
    type: ResponseMcpListToolsInProgressEventDto.TypeEnum;
}
export namespace ResponseMcpListToolsInProgressEventDto {
    export const TypeEnum = {
        ResponseMcpListToolsInProgress: 'response.mcp_list_tools.in_progress'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


