/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogsDto } from './logsDto';
import { ImageDto } from './imageDto';


/**
 * @type ResponseCodeInterpreterToolCallDtoOutputsInner
 * @export
 */
export type ResponseCodeInterpreterToolCallDtoOutputsInner = ImageDto | LogsDto;

