/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PartDto } from './partDto';


export interface ResponseReasoningSummaryPartAddedEventDto { 
    /**
     * The ID of the item this summary part is associated with.
     */
    item_id: string;
    /**
     * The index of the output item this summary part is associated with.
     */
    output_index: number;
    /**
     * The summary part that was added.
     */
    part: PartDto;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The index of the summary part within the reasoning summary.
     */
    summary_index: number;
    /**
     * The type of the event. Always `response.reasoning_summary_part.added`.
     */
    type: ResponseReasoningSummaryPartAddedEventDto.TypeEnum;
}
export namespace ResponseReasoningSummaryPartAddedEventDto {
    export const TypeEnum = {
        ResponseReasoningSummaryPartAdded: 'response.reasoning_summary_part.added'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


