/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseInputFileContentDto { 
    /**
     * The type of the input item. Always `input_file`.
     */
    type: ResponseInputFileContentDto.TypeEnum;
    /**
     * The base64-encoded data of the file to be sent to the model.
     */
    file_data?: string;
    /**
     * The ID of the file to be sent to the model.
     */
    file_id?: string;
    /**
     * The URL of the file to be sent to the model.
     */
    file_url?: string;
    /**
     * The name of the file to be sent to the model.
     */
    filename?: string;
}
export namespace ResponseInputFileContentDto {
    export const TypeEnum = {
        InputFile: 'input_file'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


