/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseLocalEnvironmentDto } from './responseLocalEnvironmentDto';
import { ResponseContainerReferenceDto } from './responseContainerReferenceDto';


/**
 * Represents the use of a local environment to perform shell actions.
 */
/**
 * @type ResponseFunctionShellToolCallDtoEnvironment
 * Represents the use of a local environment to perform shell actions.
 * @export
 */
export type ResponseFunctionShellToolCallDtoEnvironment = ResponseContainerReferenceDto | ResponseLocalEnvironmentDto;

