/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseConversationParamDto } from './responseConversationParamDto';


/**
 * The conversation that this response belongs to. Items from this conversation are   prepended to `input_items` for this response request. Input items and output   items from this response are automatically added to this conversation after this   response completes.
 */
/**
 * @type ResponseCreateParamsNonStreamingDtoConversation
 * The conversation that this response belongs to. Items from this conversation are   prepended to `input_items` for this response request. Input items and output   items from this response are automatically added to this conversation after this   response completes.
 * @export
 */
export type ResponseCreateParamsNonStreamingDtoConversation = ResponseConversationParamDto | string;

