/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseFunctionShellCallOutputContentDtoOutcome } from './responseFunctionShellCallOutputContentDtoOutcome';


export interface ResponseFunctionShellCallOutputContentDto { 
    outcome: ResponseFunctionShellCallOutputContentDtoOutcome;
    /**
     * Captured stderr output for the shell call.
     */
    stderr: string;
    /**
     * Captured stdout output for the shell call.
     */
    stdout: string;
}

