/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseAudioTranscriptDoneEventDto { 
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always `response.audio.transcript.done`.
     */
    type: ResponseAudioTranscriptDoneEventDto.TypeEnum;
}
export namespace ResponseAudioTranscriptDoneEventDto {
    export const TypeEnum = {
        ResponseAudioTranscriptDone: 'response.audio.transcript.done'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


