/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseFileSearchCallCompletedEventDto { 
    /**
     * The ID of the output item that the file search call is initiated.
     */
    item_id: string;
    /**
     * The index of the output item that the file search call is initiated.
     */
    output_index: number;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always `response.file_search_call.completed`.
     */
    type: ResponseFileSearchCallCompletedEventDto.TypeEnum;
}
export namespace ResponseFileSearchCallCompletedEventDto {
    export const TypeEnum = {
        ResponseFileSearchCallCompleted: 'response.file_search_call.completed'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


