/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseDto } from './responseDto';


export interface ResponseCompletedEventDto { 
    /**
     * Properties of the completed response.
     */
    response: ResponseDto;
    /**
     * The sequence number for this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always `response.completed`.
     */
    type: ResponseCompletedEventDto.TypeEnum;
}
export namespace ResponseCompletedEventDto {
    export const TypeEnum = {
        ResponseCompleted: 'response.completed'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


