/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseApplyPatchToolCallOutputDto { 
    /**
     * The unique ID of the apply patch tool call output. Populated when this item is   returned via API.
     */
    id: string;
    /**
     * The unique ID of the apply patch tool call generated by the model.
     */
    call_id: string;
    /**
     * The status of the apply patch tool call output. One of `completed` or `failed`.
     */
    status: ResponseApplyPatchToolCallOutputDto.StatusEnum;
    /**
     * The type of the item. Always `apply_patch_call_output`.
     */
    type: ResponseApplyPatchToolCallOutputDto.TypeEnum;
    /**
     * The ID of the entity that created this tool call output.
     */
    created_by?: string;
    /**
     * Optional textual output returned by the apply patch tool.
     */
    output?: string;
}
export namespace ResponseApplyPatchToolCallOutputDto {
    export const StatusEnum = {
        Completed: 'completed',
        Failed: 'failed'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const TypeEnum = {
        ApplyPatchCallOutput: 'apply_patch_call_output'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


