/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExitDto } from './exitDto';
import { TimeoutDto } from './timeoutDto';


/**
 * The exit or timeout outcome associated with this shell call.
 */
/**
 * @type ResponseFunctionShellCallOutputContentDtoOutcome
 * The exit or timeout outcome associated with this shell call.
 * @export
 */
export type ResponseFunctionShellCallOutputContentDtoOutcome = ExitDto | TimeoutDto;

