/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseRefusalDoneEventDto { 
    /**
     * The index of the content part that the refusal text is finalized.
     */
    content_index: number;
    /**
     * The ID of the output item that the refusal text is finalized.
     */
    item_id: string;
    /**
     * The index of the output item that the refusal text is finalized.
     */
    output_index: number;
    /**
     * The refusal text that is finalized.
     */
    refusal: string;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always `response.refusal.done`.
     */
    type: ResponseRefusalDoneEventDto.TypeEnum;
}
export namespace ResponseRefusalDoneEventDto {
    export const TypeEnum = {
        ResponseRefusalDone: 'response.refusal.done'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


