/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseErrorEventDto { 
    /**
     * The error code.
     */
    code: string;
    /**
     * The error message.
     */
    message: string;
    /**
     * The error parameter.
     */
    param: string;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always `error`.
     */
    type: ResponseErrorEventDto.TypeEnum;
}
export namespace ResponseErrorEventDto {
    export const TypeEnum = {
        Error: 'error'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


