/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseContentPartAddedEventDtoPart } from './responseContentPartAddedEventDtoPart';


export interface ResponseContentPartAddedEventDto { 
    /**
     * The index of the content part that was added.
     */
    content_index: number;
    /**
     * The ID of the output item that the content part was added to.
     */
    item_id: string;
    /**
     * The index of the output item that the content part was added to.
     */
    output_index: number;
    part: ResponseContentPartAddedEventDtoPart;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always `response.content_part.added`.
     */
    type: ResponseContentPartAddedEventDto.TypeEnum;
}
export namespace ResponseContentPartAddedEventDto {
    export const TypeEnum = {
        ResponseContentPartAdded: 'response.content_part.added'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


