/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseAudioDeltaEventDto { 
    /**
     * A chunk of Base64 encoded response audio bytes.
     */
    delta: string;
    /**
     * A sequence number for this chunk of the stream response.
     */
    sequence_number: number;
    /**
     * The type of the event. Always `response.audio.delta`.
     */
    type: ResponseAudioDeltaEventDto.TypeEnum;
}
export namespace ResponseAudioDeltaEventDto {
    export const TypeEnum = {
        ResponseAudioDelta: 'response.audio.delta'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


