/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PathDto } from './pathDto';
import { KeypressDto } from './keypressDto';
import { ClickDto } from './clickDto';
import { MoveDto } from './moveDto';
import { ScrollDto } from './scrollDto';
import { TypeDto } from './typeDto';
import { DoubleClickDto } from './doubleClickDto';
import { WaitDto } from './waitDto';
import { DragDto } from './dragDto';
import { ScreenshotDto } from './screenshotDto';


/**
 * A click action.
 */
/**
 * @type ResponseComputerToolCallDtoAction
 * A click action.
 * @export
 */
export type ResponseComputerToolCallDtoAction = ClickDto | DoubleClickDto | DragDto | KeypressDto | MoveDto | ScreenshotDto | ScrollDto | TypeDto | WaitDto;

