/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseOutputItemDoneEventDtoItem } from './responseOutputItemDoneEventDtoItem';


export interface ResponseOutputItemDoneEventDto { 
    item: ResponseOutputItemDoneEventDtoItem;
    /**
     * The index of the output item that was marked done.
     */
    output_index: number;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always `response.output_item.done`.
     */
    type: ResponseOutputItemDoneEventDto.TypeEnum;
}
export namespace ResponseOutputItemDoneEventDto {
    export const TypeEnum = {
        ResponseOutputItemDone: 'response.output_item.done'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


