/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseFormatTextJSONSchemaConfigDto { 
    /**
     * The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores   and dashes, with a maximum length of 64.
     */
    name: string;
    /**
     * The schema for the response format, described as a JSON Schema object. Learn how   to build JSON schemas [here](https://json-schema.org/).
     */
    schema: object;
    /**
     * The type of response format being defined. Always `json_schema`.
     */
    type: ResponseFormatTextJSONSchemaConfigDto.TypeEnum;
    /**
     * A description of what the response format is for, used by the model to determine   how to respond in the format.
     */
    description?: string;
    /**
     * Whether to enable strict schema adherence when generating the output. If set to   true, the model will always follow the exact schema defined in the `schema`   field. Only a subset of JSON Schema is supported when `strict` is `true`. To   learn more, read the   [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).
     */
    strict?: object;
}
export namespace ResponseFormatTextJSONSchemaConfigDto {
    export const TypeEnum = {
        JsonSchema: 'json_schema'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


