/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseLocalEnvironmentDto { 
    /**
     * The environment type. Always `local`.
     */
    type: ResponseLocalEnvironmentDto.TypeEnum;
}
export namespace ResponseLocalEnvironmentDto {
    export const TypeEnum = {
        Local: 'local'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


