/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseInputTextContentDto { 
    /**
     * The text input to the model.
     */
    text: string;
    /**
     * The type of the input item. Always `input_text`.
     */
    type: ResponseInputTextContentDto.TypeEnum;
}
export namespace ResponseInputTextContentDto {
    export const TypeEnum = {
        InputText: 'input_text'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


