/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FunctionToolDto } from './functionToolDto';
import { ComputerToolDto } from './computerToolDto';
import { FunctionShellToolDto } from './functionShellToolDto';
import { McpDtoAllowedToolsInner } from './mcpDtoAllowedToolsInner';
import { FiltersDto } from './filtersDto';
import { McpDto } from './mcpDto';
import { WebSearchPreviewToolDto } from './webSearchPreviewToolDto';
import { ToolSearchToolDto } from './toolSearchToolDto';
import { ImageGenerationDtoModel } from './imageGenerationDtoModel';
import { CodeInterpreterDtoContainer } from './codeInterpreterDtoContainer';
import { CustomToolDto } from './customToolDto';
import { CustomToolDtoFormat } from './customToolDtoFormat';
import { FileSearchToolDto } from './fileSearchToolDto';
import { NamespaceToolDto } from './namespaceToolDto';
import { InputImageMaskDto } from './inputImageMaskDto';
import { NamespaceToolDtoToolsInner } from './namespaceToolDtoToolsInner';
import { UserLocationDto } from './userLocationDto';
import { WebSearchToolDto } from './webSearchToolDto';
import { McpDtoRequireApproval } from './mcpDtoRequireApproval';
import { RankingOptionsDto } from './rankingOptionsDto';
import { FunctionShellToolDtoEnvironment } from './functionShellToolDtoEnvironment';
import { ImageGenerationDto } from './imageGenerationDto';
import { LocalShellDto } from './localShellDto';
import { CodeInterpreterDto } from './codeInterpreterDto';
import { ComputerUsePreviewToolDto } from './computerUsePreviewToolDto';
import { ApplyPatchToolDto } from './applyPatchToolDto';


/**
 * @type ResponseToolSearchOutputItemParamDtoToolsInner
 * @export
 */
export type ResponseToolSearchOutputItemParamDtoToolsInner = ApplyPatchToolDto | CodeInterpreterDto | ComputerToolDto | ComputerUsePreviewToolDto | CustomToolDto | FileSearchToolDto | FunctionShellToolDto | FunctionToolDto | ImageGenerationDto | LocalShellDto | McpDto | NamespaceToolDto | ToolSearchToolDto | WebSearchPreviewToolDto | WebSearchToolDto;

