/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseMcpListToolsFailedEventDto { 
    /**
     * The ID of the MCP tool call item that failed.
     */
    item_id: string;
    /**
     * The index of the output item that failed.
     */
    output_index: number;
    /**
     * The sequence number of this event.
     */
    sequence_number: number;
    /**
     * The type of the event. Always \'response.mcp_list_tools.failed\'.
     */
    type: ResponseMcpListToolsFailedEventDto.TypeEnum;
}
export namespace ResponseMcpListToolsFailedEventDto {
    export const TypeEnum = {
        ResponseMcpListToolsFailed: 'response.mcp_list_tools.failed'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


