/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContainerFileCitationDto } from './containerFileCitationDto';
import { FilePathDto } from './filePathDto';
import { FileCitationDto } from './fileCitationDto';
import { URLCitationDto } from './uRLCitationDto';


/**
 * @type ResponseOutputTextDtoAnnotationsInner
 * @export
 */
export type ResponseOutputTextDtoAnnotationsInner = ContainerFileCitationDto | FileCitationDto | FilePathDto | URLCitationDto;

