/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScrollDto { 
    /**
     * The horizontal scroll distance.
     */
    scroll_x: number;
    /**
     * The vertical scroll distance.
     */
    scroll_y: number;
    /**
     * Specifies the event type. For a scroll action, this property is always set to   `scroll`.
     */
    type: ScrollDto.TypeEnum;
    /**
     * The x-coordinate where the scroll occurred.
     */
    x: number;
    /**
     * The y-coordinate where the scroll occurred.
     */
    y: number;
    /**
     * The keys being held while scrolling.
     */
    keys?: Array<string>;
}
export namespace ScrollDto {
    export const TypeEnum = {
        Scroll: 'scroll'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


