/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceDto } from './sourceDto';


export interface SearchDto { 
    /**
     * [DEPRECATED] The search query.
     */
    query: string;
    /**
     * The action type.
     */
    type: SearchDto.TypeEnum;
    /**
     * The search queries.
     */
    queries?: Array<string>;
    /**
     * The sources used in the search.
     */
    sources?: Array<SourceDto>;
}
export namespace SearchDto {
    export const TypeEnum = {
        Search: 'search'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


