/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionDto } from './actionDto';
import { ShellCallDtoEnvironment } from './shellCallDtoEnvironment';


export interface ShellCallDto { 
    /**
     * The shell commands and limits that describe how to run the tool call.
     */
    action: ActionDto;
    /**
     * The unique ID of the shell tool call generated by the model.
     */
    call_id: string;
    /**
     * The type of the item. Always `shell_call`.
     */
    type: ShellCallDto.TypeEnum;
    /**
     * The unique ID of the shell tool call. Populated when this item is returned via   API.
     */
    id?: string;
    environment?: ShellCallDtoEnvironment;
    /**
     * The status of the shell call. One of `in_progress`, `completed`, or   `incomplete`.
     */
    status?: ShellCallDto.StatusEnum;
}
export namespace ShellCallDto {
    export const TypeEnum = {
        ShellCall: 'shell_call'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const StatusEnum = {
        InProgress: 'in_progress',
        Completed: 'completed',
        Incomplete: 'incomplete'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


