/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SkillReferenceDto { 
    /**
     * The ID of the referenced skill.
     */
    skill_id: string;
    /**
     * References a skill created with the /v1/skills endpoint.
     */
    type: SkillReferenceDto.TypeEnum;
    /**
     * Optional skill version. Use a positive integer or \'latest\'. Omit for default.
     */
    version?: string;
}
export namespace SkillReferenceDto {
    export const TypeEnum = {
        SkillReference: 'skill_reference'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


