/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SourceDto { 
    /**
     * The type of source. Always `url`.
     */
    type: SourceDto.TypeEnum;
    /**
     * The URL of the source.
     */
    url: string;
}
export namespace SourceDto {
    export const TypeEnum = {
        Url: 'url'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


