/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SummaryDto { 
    /**
     * A summary of the reasoning output from the model so far.
     */
    text: string;
    /**
     * The type of the object. Always `summary_text`.
     */
    type: SummaryDto.TypeEnum;
}
export namespace SummaryDto {
    export const TypeEnum = {
        SummaryText: 'summary_text'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


