/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ToolDto { 
    /**
     * The JSON schema describing the tool\'s input.
     */
    input_schema: object;
    /**
     * The name of the tool.
     */
    name: string;
    /**
     * Additional annotations about the tool.
     */
    annotations?: object;
    /**
     * The description of the tool.
     */
    description?: string;
}

