/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ToolSearchCallDto { 
    /**
     * The arguments supplied to the tool search call.
     */
    arguments: object;
    /**
     * The item type. Always `tool_search_call`.
     */
    type: ToolSearchCallDto.TypeEnum;
    /**
     * The unique ID of this tool search call.
     */
    id?: string;
    /**
     * The unique ID of the tool search call generated by the model.
     */
    call_id?: string;
    /**
     * Whether tool search was executed by the server or by the client.
     */
    execution?: ToolSearchCallDto.ExecutionEnum;
    /**
     * The status of the tool search call.
     */
    status?: ToolSearchCallDto.StatusEnum;
}
export namespace ToolSearchCallDto {
    export const TypeEnum = {
        ToolSearchCall: 'tool_search_call'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const ExecutionEnum = {
        Server: 'server',
        Client: 'client'
    } as const;
    export type ExecutionEnum = typeof ExecutionEnum[keyof typeof ExecutionEnum];
    export const StatusEnum = {
        InProgress: 'in_progress',
        Completed: 'completed',
        Incomplete: 'incomplete'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


