/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ToolChoiceApplyPatchDto { 
    /**
     * The tool to call. Always `apply_patch`.
     */
    type: ToolChoiceApplyPatchDto.TypeEnum;
}
export namespace ToolChoiceApplyPatchDto {
    export const TypeEnum = {
        ApplyPatch: 'apply_patch'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


