/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ToolChoiceTypesDto { 
    /**
     * The type of hosted tool the model should to use. Learn more about   [built-in tools](https://platform.openai.com/docs/guides/tools).      Allowed values are:      - `file_search`   - `web_search_preview`   - `computer`   - `computer_use_preview`   - `computer_use`   - `code_interpreter`   - `mcp`   - `image_generation`
     */
    type: ToolChoiceTypesDto.TypeEnum;
}
export namespace ToolChoiceTypesDto {
    export const TypeEnum = {
        FileSearch: 'file_search',
        Computer: 'computer',
        ComputerUsePreview: 'computer_use_preview',
        Mcp: 'mcp',
        CodeInterpreter: 'code_interpreter',
        ImageGeneration: 'image_generation',
        WebSearchPreview: 'web_search_preview',
        WebSearchPreview20250311: 'web_search_preview_2025_03_11',
        ComputerUse: 'computer_use'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


