/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ToolChoiceCustomDto { 
    /**
     * The name of the custom tool to call.
     */
    name: string;
    /**
     * For custom tool calling, the type is always `custom`.
     */
    type: ToolChoiceCustomDto.TypeEnum;
}
export namespace ToolChoiceCustomDto {
    export const TypeEnum = {
        Custom: 'custom'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


