/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProviderInfoDto } from './providerInfoDto';


export interface ToolCallOutputDto { 
    type: ToolCallOutputDto.TypeEnum;
    tool: string;
    arguments: object;
    output: string;
    provider_info: ProviderInfoDto;
}
export namespace ToolCallOutputDto {
    export const TypeEnum = {
        ToolCall: 'tool_call'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


