/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ToolSearchToolDto { 
    /**
     * The type of the tool. Always `tool_search`.
     */
    type: ToolSearchToolDto.TypeEnum;
    /**
     * Description shown to the model for a client-executed tool search tool.
     */
    description?: string;
    /**
     * Whether tool search is executed by the server or by the client.
     */
    execution?: ToolSearchToolDto.ExecutionEnum;
    /**
     * Parameter schema for a client-executed tool search tool.
     */
    parameters?: object;
}
export namespace ToolSearchToolDto {
    export const TypeEnum = {
        ToolSearch: 'tool_search'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const ExecutionEnum = {
        Server: 'server',
        Client: 'client'
    } as const;
    export type ExecutionEnum = typeof ExecutionEnum[keyof typeof ExecutionEnum];
}


