/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserLocationDto } from './userLocationDto';


export interface WebSearchOptionsDto { 
    /**
     * High level guidance for the amount of context window space to use for the   search. One of `low`, `medium`, or `high`. `medium` is the default.
     */
    search_context_size?: WebSearchOptionsDto.SearchContextSizeEnum;
    /**
     * Approximate location parameters for the search.
     */
    user_location?: UserLocationDto;
}
export namespace WebSearchOptionsDto {
    export const SearchContextSizeEnum = {
        Low: 'low',
        High: 'high',
        Medium: 'medium'
    } as const;
    export type SearchContextSizeEnum = typeof SearchContextSizeEnum[keyof typeof SearchContextSizeEnum];
}


