/**
 * LMStudio Wrapper API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserLocationDto } from './userLocationDto';


export interface WebSearchPreviewToolDto { 
    /**
     * The type of the web search tool. One of `web_search_preview` or   `web_search_preview_2025_03_11`.
     */
    type: WebSearchPreviewToolDto.TypeEnum;
    search_content_types?: Array<WebSearchPreviewToolDto.SearchContentTypesEnum>;
    /**
     * High level guidance for the amount of context window space to use for the   search. One of `low`, `medium`, or `high`. `medium` is the default.
     */
    search_context_size?: WebSearchPreviewToolDto.SearchContextSizeEnum;
    /**
     * The user\'s location.
     */
    user_location?: UserLocationDto;
}
export namespace WebSearchPreviewToolDto {
    export const TypeEnum = {
        WebSearchPreview: 'web_search_preview',
        WebSearchPreview20250311: 'web_search_preview_2025_03_11'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const SearchContentTypesEnum = {
        Text: 'text',
        Image: 'image'
    } as const;
    export type SearchContentTypesEnum = typeof SearchContentTypesEnum[keyof typeof SearchContentTypesEnum];
    export const SearchContextSizeEnum = {
        Low: 'low',
        High: 'high',
        Medium: 'medium'
    } as const;
    export type SearchContextSizeEnum = typeof SearchContextSizeEnum[keyof typeof SearchContextSizeEnum];
}


