import { ApiProperty } from '@nestjs/swagger';
import { Equals, IsArray, IsIn, IsOptional, IsString, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

import { OutputDto } from './OutputDto';

export class ResponseFunctionShellToolCallOutputDto {
  /**
   * The unique ID of the shell call output. Populated when this item is returned via
   * API.
   */
  @ApiProperty({
    description: `The unique ID of the shell call output. Populated when this item is returned via
  API.`,
    type: 'string',
  })
  @IsString()
  id!: string;

  /** The unique ID of the shell tool call generated by the model. */
  @ApiProperty({
    description: `The unique ID of the shell tool call generated by the model.`,
    type: 'string',
  })
  @IsString()
  call_id!: string;

  /**
   * The maximum length of the shell command output. This is generated by the model
   * and should be passed back with the raw output.
   */
  @ApiProperty({
    description: `The maximum length of the shell command output. This is generated by the model
  and should be passed back with the raw output.`,
    type: 'number',
  })
  max_output_length!: null | number;

  /** An array of shell call output contents */
  @ApiProperty({
    description: `An array of shell call output contents`,
    type: OutputDto,
    isArray: true,
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => OutputDto)
  output!: OutputDto[];

  /**
   * The status of the shell call output. One of `in_progress`, `completed`, or
   * `incomplete`.
   */
  @ApiProperty({
    description: `The status of the shell call output. One of \`in_progress\`, \`completed\`, or
  \`incomplete\`.`,
    enum: ['in_progress', 'completed', 'incomplete'],
  })
  @IsIn(['in_progress', 'completed', 'incomplete'])
  status!: 'in_progress' | 'completed' | 'incomplete';

  /** The type of the shell call output. Always `shell_call_output`. */
  @ApiProperty({
    description: `The type of the shell call output. Always \`shell_call_output\`.`,
    example: 'shell_call_output',
  })
  @Equals('shell_call_output')
  type!: 'shell_call_output';

  /** The identifier of the actor that created the item. */
  @ApiProperty({
    required: false,
    description: `The identifier of the actor that created the item.`,
    type: 'string',
  })
  @IsOptional()
  @IsString()
  created_by?: string;
}
