import { ApiProperty } from '@nestjs/swagger';
import { Equals, IsArray, IsIn, IsOptional, IsString, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

import { ResponseFunctionShellCallOutputContentDto } from './ResponseFunctionShellCallOutputContentDto';

export class ShellCallOutputDto {
  /** The unique ID of the shell tool call generated by the model. */
  @ApiProperty({
    description: `The unique ID of the shell tool call generated by the model.`,
    type: 'string',
  })
  @IsString()
  call_id!: string;

  /**
   * Captured chunks of stdout and stderr output, along with their associated
   * outcomes.
   */
  @ApiProperty({
    description: `Captured chunks of stdout and stderr output, along with their associated
  outcomes.`,
    type: ResponseFunctionShellCallOutputContentDto,
    isArray: true,
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ResponseFunctionShellCallOutputContentDto)
  output!: ResponseFunctionShellCallOutputContentDto[];

  /** The type of the item. Always `shell_call_output`. */
  @ApiProperty({
    description: `The type of the item. Always \`shell_call_output\`.`,
    type: 'string',
    enum: ['shell_call_output'],
  })
  @Equals('shell_call_output')
  type!: 'shell_call_output';

  /**
   * The unique ID of the shell tool call output. Populated when this item is
   * returned via API.
   */
  @ApiProperty({
    required: false,
    description: `The unique ID of the shell tool call output. Populated when this item is
  returned via API.`,
    type: 'string',
  })
  @IsOptional()
  id?: null | string;

  /**
   * The maximum number of UTF-8 characters captured for this shell call's combined
   * output.
   */
  @ApiProperty({
    required: false,
    description: `The maximum number of UTF-8 characters captured for this shell call's combined
  output.`,
    type: 'number',
  })
  @IsOptional()
  max_output_length?: null | number;

  /** The status of the shell call output. */
  @ApiProperty({
    required: false,
    description: `The status of the shell call output.`,
    enum: ['in_progress', 'completed', 'incomplete'],
  })
  @IsOptional()
  @IsIn(['in_progress', 'completed', 'incomplete'])
  status?: null | 'in_progress' | 'completed' | 'incomplete';
}
