import { ApiExtraModels, ApiProperty, getSchemaPath } from '@nestjs/swagger';
import { Equals, IsIn, IsOptional, IsString, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

import { ActionDto } from './ActionDto';
import { LocalEnvironmentDto } from './LocalEnvironmentDto';
import { ContainerReferenceDto } from './ContainerReferenceDto';

@ApiExtraModels(
  LocalEnvironmentDto,
  ContainerReferenceDto,
)
export class ShellCallDto {
  /** The shell commands and limits that describe how to run the tool call. */
  @ApiProperty({
    description: `The shell commands and limits that describe how to run the tool call.`,
    type: () => ActionDto,
  })
  @ValidateNested()
  @Type(() => ActionDto)
  action!: ActionDto;

  /** The unique ID of the shell tool call generated by the model. */
  @ApiProperty({
    description: `The unique ID of the shell tool call generated by the model.`,
    type: 'string',
  })
  @IsString()
  call_id!: string;

  /** The type of the item. Always `shell_call`. */
  @ApiProperty({
    description: `The type of the item. Always \`shell_call\`.`,
    example: 'shell_call',
  })
  @Equals('shell_call')
  type!: 'shell_call';

  /**
   * The unique ID of the shell tool call. Populated when this item is returned via
   * API.
   */
  @ApiProperty({
    required: false,
    description: `The unique ID of the shell tool call. Populated when this item is returned via
  API.`,
    type: 'string',
  })
  @IsOptional()
  id?: null | string;

  /** The environment to execute the shell commands in. */
  @ApiProperty({
    required: false,
    description: `The environment to execute the shell commands in.`,
    oneOf: [
      { $ref: getSchemaPath(LocalEnvironmentDto) },
      { $ref: getSchemaPath(ContainerReferenceDto) },
    ],
  })
  @IsOptional()
  environment?: null | LocalEnvironmentDto | ContainerReferenceDto;

  /**
   * The status of the shell call. One of `in_progress`, `completed`, or
   * `incomplete`.
   */
  @ApiProperty({
    required: false,
    description: `The status of the shell call. One of \`in_progress\`, \`completed\`, or
  \`incomplete\`.`,
    enum: ['in_progress', 'completed', 'incomplete'],
  })
  @IsOptional()
  @IsIn(['in_progress', 'completed', 'incomplete'])
  status?: null | 'in_progress' | 'completed' | 'incomplete';
}
