import { ApiExtraModels, ApiProperty, getSchemaPath } from '@nestjs/swagger';
import { Equals, IsArray, IsOptional, IsString } from 'class-validator';

import { AudioDto } from './AudioDto';
import { ChatCompletionContentPartTextDto } from './ChatCompletionContentPartTextDto';
import { ChatCompletionContentPartRefusalDto } from './ChatCompletionContentPartRefusalDto';
import { FunctionCallDto } from './FunctionCallDto';
import { ChatCompletionMessageFunctionToolCallDto } from './ChatCompletionMessageFunctionToolCallDto';
import { ChatCompletionMessageCustomToolCallDto } from './ChatCompletionMessageCustomToolCallDto';

@ApiExtraModels(
  AudioDto,
  ChatCompletionContentPartTextDto,
  ChatCompletionContentPartRefusalDto,
  FunctionCallDto,
  ChatCompletionMessageFunctionToolCallDto,
  ChatCompletionMessageCustomToolCallDto,
)
export class ChatCompletionAssistantMessageParamDto {
  /** The role of the messages author, in this case `assistant`. */
  @ApiProperty({
    description: `The role of the messages author, in this case \`assistant\`.`,
    type: 'string',
    enum: ['assistant'],
  })
  @Equals('assistant')
  role!: 'assistant';

  /**
   * Data about a previous audio response from the model.
   * [Learn more](https://platform.openai.com/docs/guides/audio).
   */
  @ApiProperty({
    required: false,
    description: `Data about a previous audio response from the model.
  [Learn more](https://platform.openai.com/docs/guides/audio).`,
    type: () => AudioDto,
  })
  @IsOptional()
  audio?: null | AudioDto;

  /**
   * The contents of the assistant message. Required unless `tool_calls` or
   * `function_call` is specified.
   */
  @ApiProperty({
    required: false,
    description: `The contents of the assistant message. Required unless \`tool_calls\` or
  \`function_call\` is specified.`,
    isArray: true,
    oneOf: [
      { type: 'string' },
      { $ref: getSchemaPath(ChatCompletionContentPartTextDto) },
      { $ref: getSchemaPath(ChatCompletionContentPartRefusalDto) },
    ],
  })
  @IsOptional()
  content?: null | string | (ChatCompletionContentPartTextDto | ChatCompletionContentPartRefusalDto)[];

  @ApiProperty({
    required: false,
    type: () => FunctionCallDto,
  })
  @IsOptional()
  function_call?: null | FunctionCallDto;

  /**
   * An optional name for the participant. Provides the model information to
   * differentiate between participants of the same role.
   */
  @ApiProperty({
    required: false,
    description: `An optional name for the participant. Provides the model information to
  differentiate between participants of the same role.`,
    type: 'string',
  })
  @IsOptional()
  @IsString()
  name?: string;

  /** The refusal message by the assistant. */
  @ApiProperty({
    required: false,
    description: `The refusal message by the assistant.`,
    type: 'string',
  })
  @IsOptional()
  refusal?: null | string;

  /** The tool calls generated by the model, such as function calls. */
  @ApiProperty({
    required: false,
    description: `The tool calls generated by the model, such as function calls.`,
    isArray: true,
    oneOf: [
      { $ref: getSchemaPath(ChatCompletionMessageFunctionToolCallDto) },
      { $ref: getSchemaPath(ChatCompletionMessageCustomToolCallDto) },
    ],
  })
  @IsOptional()
  @IsArray()
  tool_calls?: (ChatCompletionMessageFunctionToolCallDto | ChatCompletionMessageCustomToolCallDto)[];
}
