import { ApiProperty } from '@nestjs/swagger';
import { IsNumber, IsString } from 'class-validator';

export class ChatCompletionAudioDto {
  /** Unique identifier for this audio response. */
  @ApiProperty({
    description: `Unique identifier for this audio response.`,
    type: 'string',
  })
  @IsString()
  id!: string;

  /**
   * Base64 encoded audio bytes generated by the model, in the format specified in
   * the request.
   */
  @ApiProperty({
    description: `Base64 encoded audio bytes generated by the model, in the format specified in
  the request.`,
    type: 'string',
  })
  @IsString()
  data!: string;

  /**
   * The Unix timestamp (in seconds) for when this audio response will no longer be
   * accessible on the server for use in multi-turn conversations.
   */
  @ApiProperty({
    description: `The Unix timestamp (in seconds) for when this audio response will no longer be
  accessible on the server for use in multi-turn conversations.`,
    type: 'number',
  })
  @IsNumber()
  expires_at!: number;

  /** Transcript of the audio generated by the model. */
  @ApiProperty({
    description: `Transcript of the audio generated by the model.`,
    type: 'string',
  })
  @IsString()
  transcript!: string;
}
