import { ApiExtraModels, ApiProperty, getSchemaPath } from '@nestjs/swagger';
import { Equals, IsArray, IsOptional, IsString, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

import { AnnotationDto } from './AnnotationDto';
import { ChatCompletionAudioDto } from './ChatCompletionAudioDto';
import { FunctionCallDto } from './FunctionCallDto';
import { ChatCompletionMessageFunctionToolCallDto } from './ChatCompletionMessageFunctionToolCallDto';
import { ChatCompletionMessageCustomToolCallDto } from './ChatCompletionMessageCustomToolCallDto';
import { ChatCompletionContentPartTextDto } from './ChatCompletionContentPartTextDto';
import { ChatCompletionContentPartImageDto } from './ChatCompletionContentPartImageDto';

@ApiExtraModels(
  ChatCompletionAudioDto,
  FunctionCallDto,
  ChatCompletionMessageFunctionToolCallDto,
  ChatCompletionMessageCustomToolCallDto,
  ChatCompletionContentPartTextDto,
  ChatCompletionContentPartImageDto,
)
export class ChatCompletionStoreMessageDto {
  /** The contents of the message. */
  @ApiProperty({
    description: `The contents of the message.`,
    type: 'string',
  })
  content!: null | string;

  /** The refusal message generated by the model. */
  @ApiProperty({
    description: `The refusal message generated by the model.`,
    type: 'string',
  })
  refusal!: null | string;

  /** The role of the author of this message. */
  @ApiProperty({
    description: `The role of the author of this message.`,
    type: 'string',
    enum: ['assistant'],
  })
  @Equals('assistant')
  role!: 'assistant';

  /**
   * Annotations for the message, when applicable, as when using the
   * [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).
   */
  @ApiProperty({
    required: false,
    description: `Annotations for the message, when applicable, as when using the
  [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).`,
    type: AnnotationDto,
    isArray: true,
  })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => AnnotationDto)
  annotations?: AnnotationDto[];

  /**
   * If the audio output modality is requested, this object contains data about the
   * audio response from the model.
   * [Learn more](https://platform.openai.com/docs/guides/audio).
   */
  @ApiProperty({
    required: false,
    description: `If the audio output modality is requested, this object contains data about the
  audio response from the model.
  [Learn more](https://platform.openai.com/docs/guides/audio).`,
    type: () => ChatCompletionAudioDto,
  })
  @IsOptional()
  audio?: null | ChatCompletionAudioDto;

  @ApiProperty({
    required: false,
    type: () => FunctionCallDto,
  })
  @IsOptional()
  function_call?: null | FunctionCallDto;

  /** The tool calls generated by the model, such as function calls. */
  @ApiProperty({
    required: false,
    description: `The tool calls generated by the model, such as function calls.`,
    isArray: true,
    oneOf: [
      { $ref: getSchemaPath(ChatCompletionMessageFunctionToolCallDto) },
      { $ref: getSchemaPath(ChatCompletionMessageCustomToolCallDto) },
    ],
  })
  @IsOptional()
  @IsArray()
  tool_calls?: (ChatCompletionMessageFunctionToolCallDto | ChatCompletionMessageCustomToolCallDto)[];

  /** The identifier of the chat message. */
  @ApiProperty({
    description: `The identifier of the chat message.`,
    type: 'string',
  })
  @IsString()
  id!: string;

  /**
   * If a content parts array was provided, this is an array of `text` and
   * `image_url` parts. Otherwise, null.
   */
  @ApiProperty({
    required: false,
    description: `If a content parts array was provided, this is an array of \`text\` and
  \`image_url\` parts. Otherwise, null.`,
    isArray: true,
    oneOf: [
      { $ref: getSchemaPath(ChatCompletionContentPartTextDto) },
      { $ref: getSchemaPath(ChatCompletionContentPartImageDto) },
    ],
  })
  @IsOptional()
  content_parts?: null | (ChatCompletionContentPartTextDto | ChatCompletionContentPartImageDto)[];
}
