import { ApiProperty } from '@nestjs/swagger';
import { IsString } from 'class-validator';

export class CustomDto {
  /** The input for the custom tool call generated by the model. */
  @ApiProperty({
    description: `The input for the custom tool call generated by the model.`,
    type: 'string',
  })
  @IsString()
  input!: string;

  /** The name of the custom tool to call. */
  @ApiProperty({
    description: `The name of the custom tool to call.`,
    type: 'string',
  })
  @IsString()
  name!: string;
}
