import { ApiProperty } from '@nestjs/swagger';
import { IsArray, IsIn, IsOptional, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

import { FunctionCallDto } from './FunctionCallDto';
import { ToolCallDto } from './ToolCallDto';

export class DeltaDto {
  /** The contents of the chunk message. */
  @ApiProperty({
    required: false,
    description: `The contents of the chunk message.`,
    type: 'string',
  })
  @IsOptional()
  content?: null | string;

  @ApiProperty({
    required: false,
    type: () => FunctionCallDto,
  })
  @IsOptional()
  @ValidateNested()
  @Type(() => FunctionCallDto)
  function_call?: FunctionCallDto;

  /** The refusal message generated by the model. */
  @ApiProperty({
    required: false,
    description: `The refusal message generated by the model.`,
    type: 'string',
  })
  @IsOptional()
  refusal?: null | string;

  /** The role of the author of this message. */
  @ApiProperty({
    required: false,
    description: `The role of the author of this message.`,
    enum: ['developer', 'system', 'user', 'assistant', 'tool'],
  })
  @IsOptional()
  @IsIn(['developer', 'system', 'user', 'assistant', 'tool'])
  role?: 'developer' | 'system' | 'user' | 'assistant' | 'tool';

  @ApiProperty({
    required: false,
    type: ToolCallDto,
    isArray: true,
  })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ToolCallDto)
  tool_calls?: ToolCallDto[];
}
