import { ApiProperty } from '@nestjs/swagger';
import { IsString } from 'class-validator';

export class FunctionCallDto {
  /**
   * The arguments to call the function with, as generated by the model in JSON
   * format. Note that the model does not always generate valid JSON, and may
   * hallucinate parameters not defined by your function schema. Validate the
   * arguments in your code before calling your function.
   */
  @ApiProperty({
    description: `The arguments to call the function with, as generated by the model in JSON
  format. Note that the model does not always generate valid JSON, and may
  hallucinate parameters not defined by your function schema. Validate the
  arguments in your code before calling your function.`,
    type: 'string',
  })
  @IsString()
  arguments!: string;

  /** The name of the function to call. */
  @ApiProperty({
    description: `The name of the function to call.`,
    type: 'string',
  })
  @IsString()
  name!: string;
}
